# Generated by Django 4.0.4 on 2022-05-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=32)),
                ('korean_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('tel', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=32)),
                ('lat', models.CharField(max_length=32, null=True)),
                ('long', models.CharField(max_length=32, null=True)),
                ('postcode', models.CharField(max_length=32)),
                ('address_1', models.CharField(max_length=256)),
                ('address_2', models.CharField(max_length=256)),
                ('operation_time', models.CharField(max_length=128)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('etc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DinerPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='diner/images/%Y/%m/%d/%H/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('image', models.ImageField(blank=True, upload_to='menu/images/%Y/%m/%d/%H/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=32)),
                ('korean_name', models.CharField(max_length=32)),
                ('price_won', models.CharField(max_length=32)),
                ('price_dollar', models.CharField(max_length=32)),
                ('explanation', models.CharField(max_length=256)),
                ('etc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.diner')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('etc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('category_diner', models.ManyToManyField(related_name='category', to='DB.diner')),
                ('category_menus', models.ManyToManyField(related_name='category', to='DB.menu')),
            ],
        ),
    ]
