# Generated by Django 4.0.4 on 2022-05-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('etc', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='diner',
            name='lat',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='diner',
            name='long',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='diner',
            name='address_1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='diner',
            name='address_2',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='diner',
            name='area',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='FoodCategory',
        ),
        migrations.AddField(
            model_name='category',
            name='category_diner',
            field=models.ManyToManyField(related_name='category', to='DB.diner'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_menus',
            field=models.ManyToManyField(related_name='category', to='DB.menu'),
        ),
    ]
