# Generated by Django 4.0.4 on 2022-05-18 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_remove_category_category_diner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='diner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.diner'),
        ),
    ]
