# Generated by Django 4.0.4 on 2022-05-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_alter_menu_diner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diner',
            name='postcode',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
