# Generated by Django 4.0.4 on 2022-05-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_alter_diner_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diner',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
