# Generated by Django 4.0.4 on 2022-05-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_alter_diner_etc_alter_menu_etc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='etc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
