# Generated by Django 4.0.4 on 2022-05-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_alter_category_etc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinerpicture',
            name='image',
        ),
        migrations.RemoveField(
            model_name='menupicture',
            name='image',
        ),
        migrations.AddField(
            model_name='dinerpicture',
            name='diner_picture_file',
            field=models.ImageField(blank=True, upload_to='diner/diner_picture/%Y/%m/%d/%H/'),
        ),
        migrations.AddField(
            model_name='menupicture',
            name='menu_picture',
            field=models.ImageField(blank=True, upload_to='menu/menu_picture/%Y/%m/%d/%H/'),
        ),
    ]
