from DB.models import *


def create_data():
    new_diner = Diner(english_name='Hongik Sujebi', korean_name='홍익 수제비',email='null',tel='02-323-6828',area='Sangsu',lat='37.55272348187322',long='126.92382296119798',postcode='null',address_1='91, Wausan-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11am ~ 9pm')
    new_diner = Diner(english_name='Dakkoyam', korean_name='닭꼬얌',email='null',tel='02-322-3331',area='Hongdae',lat='37.55144859432923',long='126.9238610381392',postcode='null',address_1='29, Wausan-ro 18-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11:30am ~ 0am')
    new_diner = Diner(english_name='Yoonseoul', korean_name='윤서울',email='null',tel='02)336-3323',area='Hongdae',lat='37.55501899597162',long='126.9241686306375',postcode='null',address_1='1st floor, 31, Hongik-ro 2-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Wed~Sat : 6pm ~ 10pm Sun~Tue : Closed')
    new_diner = Diner(english_name='Nambuk Tong il', korean_name='남북통일',email='null',tel='02-3141-4113',area='Seogyo',lat='37.55378272103997',long='126.91794548855127',postcode='null',address_1='37, Donggyo-ro 18-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Sun : Closed Mon~Sat : 11am ~ 9:30pm')
    new_diner = Diner(english_name='Jumak Yeonnam', korean_name='연남동주막',email='null',tel='0507-1302-5664',area='Yeonnam',lat='37.5554428549012',long='126.9214001098573',postcode='null',address_1='1st floor, 145, Donggyo-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11am ~ 9pm')
    new_diner = Diner(english_name='Analog Garden', korean_name='아날로그 가든',email='null',tel='0507-1314-8560',area='Seogyo',lat='37.559091945198176',long='126.91801157229982',postcode='null',address_1='56, World Cup buk-ro 6-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 9am ~ 6pm')
    new_diner = Diner(english_name='Buttermilk', korean_name='버터밀크',email='null',tel='070-4157-1030',area='Hongdae',lat='37.559091945198176',long='126.91801157229982',postcode='null',address_1='130, Wausan-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Wed : Closed Thu~Tue : 10am ~ 5pm')
    new_diner = Diner(english_name='Gjustina', korean_name='저스티나',email='null',tel='02-332-5551',area='Hapjeong',lat='37.54786922731267',long='126.910777508728',postcode='null',address_1='1st floor, 31, Yanghwajin 2-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 10:30am ~10:30pm')
    new_diner = Diner(english_name='The April', korean_name='디 에이프릴',email='null',tel='0507-1402-0783', area='Yeonnam',lat='37.565402442631',long='126.9233318312045',postcode='null',address_1='1st floor, 19, Seongmisan-ro 29an-gil', address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Tue : Closed Mon~Fri : 11am ~ 8:30pm Sat~Sun : 10:30am ~ 8pm')
    new_diner = Diner(english_name='Ieung Ieung Ieung Ieung', korean_name='이응 이응 이응 이응',email='null',tel='0507-1351-5507',area='Sangsu',lat='37.548063296575094',long='126.92074686391085',postcode='null',address_1='63-1, Dongmak-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11am ~11pm')
    new_diner = Diner(english_name='Sujeong Okdol Saeng Sogeumgui', korean_name='수정옥돌생소금구이',email='null',tel='02-323-6292', area='Hongdae',lat='37.556265944933735',long='126.92625260856217',postcode='null',address_1='146-1, Eoulmadang-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon~Fri :  2pm ~2am Sat~Sun : 12pm ~ 2am')
    new_diner = Diner(english_name='Hanlim Don-ga', korean_name='한림돈가',email='null',tel='0507-1419-6604', area='Seogyo',lat='37.553930719085784',long='126.91699186031623',postcode='null',address_1='70, Jandari-ro, Mapo-gu', address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 4pm ~ 0am')
    new_diner = Diner(english_name='Kkul-dwaeji-jib', korean_name='꿀돼지집',email='null',tel='0507-1342-8177',area='Yeonnam',lat='37.56087566530964',long='126.92446262634971',postcode='null',address_1='236, Donggyo-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 3pm ~ 1am')
    new_diner = Diner(english_name='Yukmong', korean_name='육몽',email='null',tel='0507-1447-1149',area='Seogyo',lat='37.55319445274644',long='126.92070465039096',postcode='null',address_1='9, Yanghwa-ro 16-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 3pm ~ 0am')
    new_diner = Diner(english_name='Manyeo Curry Cream Chicken', korean_name='마녀커리크림치킨',email='null',tel='0507-1307-9336',area='Yeonnam',lat='37.56057558190233',long='126.92368197978712',postcode='null',address_1='B-103 227-5, Donggyo-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 4pm ~ 4am')
    new_diner = Diner(english_name='Ttobagi chicken', korean_name='또바기치킨',email='null',tel='02-3142-0991',area='Seogyo',lat='37.54690914389437',long='126.92282740858728',postcode='null',address_1='27, Wausan-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon~Sat : 4pm ~ 1am Sun : Closed')
    new_diner = Diner(english_name='Cheol-in chil-ho', korean_name='철인7호',email='null',tel='02-324-7175',area='Sangsu',lat='37.54849063449867',long='126.91980433105539',postcode='null',address_1='99-3, Yanghwa-ro 6-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 4pm ~ 2am')
    new_diner = Diner(english_name='Jang-jak-jib', korean_name='장작집',email='null',tel='010-3336-8844',area='Seogyo',lat='37.55824834629331',long='126.9196665497768',postcode='null',address_1='19, World Cup buk-ro 6-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon~Fri : 4:30pm ~ 0am Sat~Sun : 12:30pm ~ 0am')
    new_diner = Diner(english_name='Happy cheese smile Yeonnam', korean_name='해피치즈스마일 연남점',email='null',tel='0507-1336-6703',area='Seogyo',lat='37.561763153572954',long='126.92447304863022',postcode='null',address_1='244-1, Donggyo-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11:30am ~ 9:30pm')
    new_diner = Diner(english_name='Hongdae Maneul Tteokbokki', korean_name='홍대마늘떡볶이',email='null',tel='0507-1416-1107',area='Seogyo',lat='37.55366800557841',long='126.92149634313361',postcode='null',address_1='24, Hongik-ro 5an-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11am ~ 11pm')
    new_diner = Diner(english_name='Ddo bogetji Tteokbokki', korean_name='또보겠지떡볶이',email='null',tel='0507-1305-5819',area='Hapjeong',lat='37.549707625637396',long='126.91746900627074',postcode='null',address_1='34, Dongmak-ro 3-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11:30am ~ 9pm')
    new_diner = Diner(english_name='Hongdae Seabu-eong', korean_name='홍대씨부엉',email='null',tel='0507-1378-5253',area='Hongdae',lat='37.552569352163225',long='126.92234909210504',postcode='null',address_1='28-6, Wausan-ro 21-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11am ~ 0am')
    new_diner = Diner(english_name='Changhwadang', korean_name='창화당',email='null',tel='070-8152-0077',area='Hongdae',lat='37.559511223018305',long='126.92535529221962',postcode='null',address_1='22-6, Yanghwa-ro 23-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11:30am ~ 9pm')
    new_diner = Diner(english_name="McCOY'S", korean_name='멕코이 연남',email='null',tel='070-8648-2210',area='Yeonnam',lat='37.564183483038775',long='126.92277563668499',postcode='null',address_1='147, Seongmisan-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 9pm-9am')
    new_diner = Diner(english_name='Margaret', korean_name='마가렛',email='null',tel='070-8666-0559',area='Yeonnam',lat='37.564568666000405',long='126.92278655778959',postcode='null',address_1='10, Seongmisan-ro 29-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 12pm ~ 10pm')
    new_diner = Diner(english_name='Ance Coffee Club', korean_name='앤스커피클럽',email='null',tel='0507-1316-2954',area='Yeonnam',lat='37.56395064724011',long='126.92498300783528',postcode='null',address_1='174, Seongmisan-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 12pm ~ 9pm')
    new_diner = Diner(english_name='Colin', korean_name='콜린',email='null',tel='0507-1428-2001',area='Hapjeong',lat='37.54919384337037',long='126.92044012445012',postcode='null',address_1='35-1, Tojeong-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 11am ~ 9pm')
    new_diner = Diner(english_name='Jiri', korean_name='지리',email='null',tel='02-6396-3646',area='Hapjeong',lat='37.55007010380329',long='126.91102667786605',postcode='null',address_1='31-5, World Cup-ro 3-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon : Closed Tue~Fri : 5pm ~ 9pm Sat~Sun : 1pm ~ 9pm')
    new_diner = Diner(english_name='Tas', korean_name='타스',email='null',tel='070-4647-0447',area='Hongdae',lat='37.559196061773285',long='126.9256527015063',postcode='null',address_1='10-8, Yanghwa-ro 23-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Sun : Closed Mon~Sat : 12pm ~ 0am')
    new_diner = Diner(english_name='Soundcafe Sori', korean_name='사운드카페 소리',email='null',tel='0507-1342-1496',area='Hongdae',lat='37.55520295381149',long='126.930265637756932',postcode='null',address_1='159, Wausan-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon : Closed Tue~Thu : 6pm ~ 0am Sun : 6pm ~ 11pm')
    new_diner = Diner(english_name='Sidenote club', korean_name='사이드노트 클럽',email='null',tel='02-330-7900',area='Seogyo',lat='37.55443145738344',long='126.92128051588593',postcode='null',address_1='130, Yanghwa-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Everyday : 6pm ~ 2am')
    new_diner = Diner(english_name='Junji-eui Areumdaun Haru', korean_name='준지의 아름다운 하루',email='null',tel='02-3144-6760',area='Sangsu',lat='37.5477600347139',long='126.91864803532545',postcode='null',address_1='48, Dongmak-ro',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon : Closed Tue~Sun : 6pm ~ 4am')
    new_diner = Diner(english_name='Okta', korean_name='옥타',email='null',tel='02-325-8056',area='Yeonnam',lat='37.561967439237634',long='126.92340043163644 ',postcode='null',address_1='42, Seongmisan-ro 26-gil',address_2='Mapo-gu, Seoul, Republic of Korea',operation_time='Mon : Closed Tue~Sun : 6pm ~ 2am')

    new_category = Category(name ='Korean',etc ='null')
    new_category = Category(name ='Breakfast',etc ='null')
    new_category = Category(name ='Korean BBQ',etc ='null')
    new_category = Category(name ='Bunsik',etc ='null')
    new_category = Category(name ='Chicken',etc ='null')
    new_category = Category(name ='Night',etc ='null')
    new_category = Category(name ='Cafe',etc ='null')

    new_menu = Menu(english_name='Damdoritang', korean_name='담도리탕', price_won='25000', price_dollar='19.46',explanation='Braised chicken',etc='null') 
    new_menu = Menu(english_name='Suyuktwigim', korean_name='수육튀김', price_won='25000', price_dollar='19.46',explanation='Deep-fried boiled pork slices',etc='null') 
    new_menu = Menu(english_name='Ragu-cream tteokbokki', korean_name='라구크림떡볶이', price_won='16000', price_dollar='12.57',explanation='Ragu & cream sauce Tteokbokki',etc='null') 
    new_menu = Menu(english_name='Truffle gamjajeon', korean_name='트러플감자전', price_won='15000', price_dollar='11.78',explanation='Potato pancake with truffle',etc='null') 
    new_menu = Menu(english_name='Myeon-dubukimchi', korean_name='면두부김치', price_won='17000', price_dollar='13.35',explanation='Noodlized tofu with Kimchi',etc='null') 
    new_menu = Menu(english_name='Judamyukjeon', korean_name='주담육전', price_won='15000', price_dollar='11.78',explanation='Pan-fried Battered meat(Signature)',etc='null') 
    new_menu = Menu(english_name='Jeonbok-kalbibim', korean_name='전복칼비빔', price_won='14000', price_dollar='11.00',explanation='Spicy noodle with abalone',etc='null') 
    new_menu = Menu(english_name='Tong-ojingeo pasta', korean_name='통오징어파스타', price_won='18000', price_dollar='14.14',explanation='Pasta with whole squid',etc='null') 
    new_menu = Menu(english_name='Gamtae-han-u-yukhoe', korean_name='감태한우육회', price_won='25000', price_dollar='19.64',explanation='Sliced raw korean beef and dried seeweed',etc='null') 
    new_menu = Menu(english_name='Sujebi', korean_name='수제비', price_won='6000', price_dollar='4.71',explanation='Hand-pulled dough soup',etc='null') 
    new_menu = Menu(english_name='Dakssam', korean_name='닭쌈', price_won='18000', price_dollar='14.14',explanation='Chicken and leaf wrap',etc='null') 
    new_menu = Menu(english_name='Bulgogi Dakssam', korean_name='불고기 닭쌈', price_won='18000', price_dollar='14.14',explanation='Bulgogi chicken and leaf wrap',etc='null') 
    new_menu = Menu(english_name='Gochujang Barbeque', korean_name='고추장 바베큐', price_won='18000', price_dollar='14.17',explanation='Barbeque with red chili paste',etc='null') 
    new_menu = Menu(english_name='Dakssambab', korean_name='닭쌈밥', price_won='6000', price_dollar='4.73',explanation='Rice and leaf wrap and chicken',etc='null') 
    new_menu = Menu(english_name='Bulgogi Dakssambab', korean_name='불고기 닭쌈밥', price_won='6000', price_dollar='4.73',explanation='Rice and leaf wrap and Bulgogi chicken',etc='null') 
    new_menu = Menu(english_name='Gobabi', korean_name='고바비', price_won='12000', price_dollar='9.45',explanation='Bibimbap with red chili paste and barbeque',etc='null') 
    new_menu = Menu(english_name='Cheese gamja', korean_name='치즈감자', price_won='8000', price_dollar='6.30',explanation='Fried potato with cheese',etc='null') 
    new_menu = Menu(english_name='Dinner Course', korean_name='디너코스', price_won='58000', price_dollar='45.68',explanation='Appetizer(calamari, macadamia, etc) &lemon sherbet on oyster with hot sauce & raddish dumpling and thropule with buckwheat noodle & mussel and scallop with laver &grilled fish &deep fried shrimp, scallop &korean set with soybean paste jjigae & pineapple sherbet',etc='null') 
    new_menu = Menu(english_name='Bo-ssam', korean_name='보쌈', price_won='35000', price_dollar='27.57',explanation='Leaf wraps with pork',etc='null')
    new_menu = Menu(english_name='Mandu-jeongol', korean_name='만두전골(소)', price_won='22000', price_dollar='17.31',explanation='Dumpling hot pot for 2 people',etc='null') 
    new_menu = Menu(english_name='Mandu-jeongol-jung',korean_name='만두전골(중)', price_won='33000',price_dollar='26.07',explanation='Dumpling hot pot for 3 people', etc='null')
    new_menu = Menu(english_name='Mandu-jeongol-dae',korean_name='만두전골(대)', price_won='44000',price_dollar='34.76',explanation='Dumpling hot pot for 4 people', etc='null')
    new_menu = Menu(english_name='Mandu-guk',korean_name='만두국', price_won='9000', price_dollar='7.11',explanation='Dumpling soup', etc='null')
    new_menu = Menu(english_name='Jjin-mandu',korean_name='찐만두', price_won='9000', price_dollar='7.11',explanation='Steamed dumplings', etc='null')
    new_menu = Menu(english_name='Dak-gomtang',korean_name='닭곰탕', price_won	='9000', price_dollar='7.11',explanation='Chicken soup',etc	='null')	
    new_menu=Menu(english_name	='Sagol-Kalguksu',korean_name='사골칼국수',	price_won='9000',price_dollar='7.11',explanation='Noodle with beef bone soup', etc=	'null')
    new_menu= Menu(english_name	='Nokdu-Bindaeddeok	',korean_name='녹두빈대떡',price_won='9000',price_dollar='7.11', explanation='Mung bean pancake', etc='null')
    new_menu=Menu(english_name='Teollegi-sujebi',korean_name='털레기수제비',price_won='18000',price_dollar='14.22',explanation='Hand-pulled dough with spicy fish noodle soup',etc='null')
    new_menu=Menu(english_name='Jjukkumi-bokkeum',korean_name='쭈꾸미볶음',price_won='14000',price_dollar='11.06',explanation='Stir-fried webfoot octopus',etc='null')  	
    new_menu=Menu(english_name='Bori bap',korean_name='보리밥',price_won='8000',price_dollar='6.32',explanation='Steamed barley rice',etc='null')
    new_menu=Menu(english_name='Kodarigui',korean_name='코다리구이',price_won='16000',price_dollar='12.64',explanation='Grilled half-dried Pollack',etc='null')
    new_menu=Menu(english_name='Dongdongju',korean_name='동동주',price_won='6000',price_dollar='4.74',explanation='Korean traditional rice wine',etc='null')
    new_menu=Menu(english_name='Garden special',korean_name='가든 스페셜',price_won='18900',price_dollar='14.93',explanation='Signature menu of Analog garden',etc='null')
    new_menu=Menu(english_name='Farmers plate',korean_name='파머스 플레이트',price_won='19900',price_dollar='15.72',explanation='Smoked salmon avocado bacan poached egg and truffle',etc='null')
    new_menu=Menu(english_name='Fish out of water',korean_name='피쉬 아웃 오브 워터',price_won='14900',price_dollar='11.77',explanation='Smoked salmon, avocado and poached egg',etc='null')
    new_menu=Menu(english_name='Couscous bowl',korean_name='쿠스쿠스 보울',price_won='14900',price_dollar='11.77',explanation='Diverse salad with giant couscous',etc='null')   
    new_menu=Menu(english_name='Garden eggs',korean_name='가든 에그스',price_won='7900',price_dollar='6.24',explanation='Vegetables & herbs & breads & scrambled eggs with tomato toping',etc='null')
    new_menu=Menu(english_name='Eggs & ham',korean_name='에그스 & 햄',price_won='11900',price_dollar='9.4',explanation='Garden eggs that smoked ham added',etc='null')
    new_menu=Menu(english_name='Eggs & avocado',korean_name='에그스 & 아보카도',price_won='11900',price_dollar='9.4',explanation='Garden eggs that avocado added',etc='null')
    new_menu=Menu(english_name='Garden brunch',korean_name='가든 브런치',price_won='13900',price_dollar='10.98',explanation='Garden eggs that avocado and smoked ham added',etc='null')
    new_menu=Menu(english_name='Falafel wrap',korean_name='가든 브런치',price_won='7900',price_dollar='6.24',explanation='Falafel as a wrap',etc='null')
    new_menu=Menu(english_name='Falafel plate',korean_name='팔라펠 플레이트',price_won='12900',price_dollar='10.19',explanation='Falafel plate with vegetables',etc='null')
    new_menu=Menu(english_name='Pulled Porchetta',korean_name='풀드 포르체타',price_won='13900',price_dollar='10.98',explanation='Italian pork cuisine that baked with herbs and spices',etc='null')
    new_menu=Menu(english_name='Coconut shower',korean_name='코코넛샤워',price_won='6500',price_dollar='5.13',explanation='Espresso with coconut milk smoothie',etc='null')
    new_menu=Menu(english_name='Long black',korean_name='롱블랙',price_won='4500',price_dollar='3.55',explanation='Americano with more stronger aroma',etc='null')
    new_menu=Menu(english_name='Cold brew',korean_name='콜드브루',price_won='5500',price_dollar='4.34',explanation='',etc='null')	
    new_menu=Menu(english_name='Ricotta cheese pancake set',korean_name='리코타 치즈 팬케익 세트',price_won='8800',price_dollar='6.95',explanation='Pancake with almond and walnut & Ricotta cheese & salads & scrambled egg & bacon & potato',etc='null')	
    new_menu=Menu(english_name='Kkulttal-riyo',korean_name='꿀딸리요',price_won='7000',price_dollar='5.53',explanation='Honey & strawberry & Ricotta cheese & yogurt',etc='null')	
    new_menu=Menu(english_name='Buttermilk pancake set',korean_name='버터 밀크 팬케익세트',price_won='7800',price_dollar='6.16',explanation='Pancake with almond and walnut & salads& scrambled egg & bacon & potato',etc='null')
    new_menu=Menu(english_name='Tomato soup',korean_name='토마토 수프(10월 ~3월)',price_won='4200',price_dollar='3.32',explanation='',etc='null')	
    new_menu=Menu(english_name='Yangpa cream soup',korean_name='양파 크림 수프(10월 ~3월)',price_won='4200',price_dollar='3.32',explanation='Onion cream soup',etc='null')	
    new_menu=Menu(english_name='Gu-un tomato sandwich',korean_name='구운 토마토 샌드위치',price_won='5000',price_dollar='3.95',explanation='Sandwich with grilled tomato',etc='null')	
    new_menu=Menu(english_name='Bacon scramble egg sandwich',korean_name='베이컨 스크램블 에그 샌드위치',price_won='4500',price_dollar='3.55',explanation='Sandwich with bacon and scrambled egg',etc='null')	
    new_menu=Menu(english_name='Hand drip coffee',korean_name='핸드 드립 커피',price_won='4000',price_dollar='3.16',explanation='Brewed coffee',etc='null')	
    new_menu=Menu(english_name='Tomato juice',korean_name='토마토 주스',price_won='5000',price_dollar='3.95',explanation='',etc='null')
    new_menu=Menu(english_name='Triple-cheese pancake set',korean_name='트리플치즈 팬케익 세트',price_won='10800',price_dollar='8.53',explanation='Pancake with Gouda, Gorgonzola, Ricotta cheese & salads& scrambled egg & bacon & potato',etc='null')
    new_menu=Menu(english_name='Simple set',korean_name='심플 세트',price_won='5000',price_dollar='3.95',explanation='Toast & fried egg & cheese & ham & potato & drink(coffee, milk, sprite, coke, sparkling water)',etc='null')
    new_menu=Menu(english_name='Oneul-ui set',korean_name='오늘의 세트',price_won='6000',price_dollar='4.74',explanation="Today's sandwich & drink(coffee, milk, sprite, coke, sparkling water)", etc='null')
    new_menu=Menu(english_name='Toast set',korean_name='토스트 세트',price_won='10800',price_dollar='8.53',explanation='Salad & Caprese and grilled veges & sausage & bacon & toast & yougurt & potato & drink(coffee, milk, sprite, coke, sparkling water)',etc='null')
    new_menu=Menu(english_name='Gajeongsik suje gwail yogurt',korean_name='가정식 수제 과일 요거트',price_won='3800',price_dollar='3',explanation='Handmade and homemade fruit yogurt',etc='null')	
    new_menu=Menu(english_name='Jamong orange salad',korean_name='자몽 오렌지 샐러드',price_won='7000',price_dollar='5.53',explanation='null',etc='null')
    new_menu=Menu(english_name='Ham-cheese sandwich', korean_name='햄치즈 샌드위치',price_won='5000',price_dollar='3.95',explanation='null',etc='null')
    new_menu=Menu(english_name='Buttermilk pancake',korean_name='버터밀크 팬케익',price_won='5800',price_dollar='4.58',explanation='Signature pancake',etc='null')
    new_menu=Menu(english_name='Ricotta cheese pancake',korean_name='리코타치즈 팬케익',price_won='6800',price_dollar='5.37',explanation='Signature pancake & Ricotta cheese',etc='null')
    new_menu=Menu(english_name='Triple-cheese pancake',korean_name='트리플치즈 팬케익',price_won='7800',price_dollar='6.16',explanation='Signature pancake & Gouda, Gorgonzola, Ricotta cheese',etc='null')	
    new_menu=Menu(english_name='Gjustina brunch plate',korean_name='Gjustina 브런치 플레이트',price_won='17000',price_dollar='13.43',explanation='Scrabmled egg & homemade bacon & white mushroom & roast tomato & sourdough',etc='null')	
    new_menu=Menu(english_name='Gravlax egg benedict',korean_name='그라블락스 에그 베네딕트',price_won='17000',price_dollar='13.43',explanation='Homemade salmon Gravlax & poached egg & avocado & Hollandaise sauce & sourdough',etc='null')
    new_menu=Menu(english_name='Spice-rub pullpork egg benedict',korean_name='스파이스럽 풀포크 에그 베네딕트',price_won='18000',price_dollar='14.22',explanation='Pulled pork & poached egg & sauteed spinach & Hollandaise sauce & sourdough',etc='null')	
 	new_menu=Menu(english_name='Smashed avacado ham toast',korean_name='스매쉬드 아보카도 햄 토스트',price_won='16000',price_dollar='12.64',explanation='Avocado, parma ham, and scrambled or sunnyside poached egg with sourdough',etc='null')
 	new_menu=Menu(english_name='Smashed avacado, suran, tomato, Confit toast',korean_name='스매쉬드 아보카도, 수란, 토마토, 콩피토스트',price_won='14000',price_dollar='11.06',explanation='Avocado & tomato Confit & Parma ham & poached egg(scrambled or sunnyside) & sourdough',etc='null')	
 	new_menu=Menu(english_name='Gravlax lovers plate',korean_name='그라블락스 러버스 플레이트',price_won='21000',price_dollar='16.59',explanation='Homemade salmon Gravlax & tomato & potato salad & sourdough',etc='null')    
    new_menu=Menu(english_name='OriConfit wa orange salad',korean_name='오리콩피와 오렌지 샐러드',price_won='24000',price_dollar='18.96',explanation='Homemade duck Confit & grains & salad & orange dressing',etc='null')
	new_menu=Menu(english_name='Cowboy steak & egg',korean_name='카우보이 스테이크 & 에그',price_won='34000',price_dollar='26.86',explanation='USDA prime steak & sunny side egg',etc='null')
	new_menu=Menu(english_name='Yeon-eogui brunch, avocadowa suran',korean_name='연어구이 브런치, 아보카도와 수란',price_won='26000',price_dollar='20.54',explanation='Grilled salmon & poached egg & avocado & sourdough',etc='null')
	new_menu=Menu(english_name='Chicken avocado bowl',korean_name='치킨 아보카도 볼',price_won='19000',price_dollar='15.01',explanation='Chicken & avocado & corn-salsa bowl(kito-friendly)',etc='null')
	new_menu=Menu(english_name='Dok-ilsik pork cutlet',korean_name='독일식 포크 커틀렛',price_won='25000',price_dollar='19.75',explanation='Aged pork loin cutlet',etc='null')
	new_menu=Menu(english_name='Yuksip-sa gyup danish french toast',korean_name='64겹 Danish 프렌치 토스트',price_won='17000',price_dollar='13.43',explanation='Dansih french toast',etc='null')
	new_menu=Menu(english_name='Gjustina house salad',korean_name='Gjustina 하우스 샐러드',price_won='16000',price_dollar='12.64',explanation='Seosonal foods and fresh salad mix',etc='null')
	new_menu=Menu(english_name='Caeser salad',korean_name='시저 샐러드',price_won='16000',price_dollar='12.64',explanation='Homemade bacon & tomato & croutons & romaine & padano cheese',etc='null')
	new_menu=Menu(english_name='Orange, roast beat, grain salad',korean_name='오렌지, 로스트 비트, 그레인 샐러드',price_won='17000',price_dollar='13.43',explanation='Roast beat & orange & orange dressing & cheese & quinoa',etc='null')
	new_menu=Menu(english_name='Pojio skalete kianti keul-lasico',korean_name='포지오 스칼레테 키안티 클라시코',price_won='70000',price_dollar='55.29',explanation='More qualified pasta cooked with wine that have more acid than others',etc='null')
	new_menu=Menu(english_name='Sweet corn Carbonara',korean_name='스위트 콘 까르보나라',price_won='17000',price_dollar='13.43',explanation='Homemade bacon & sauteed diverse mushroom & sweet corn & Tagliatelle',etc='null')
	new_menu=Menu(english_name='Mortadella boe-reu baguette',korean_name='모타델라 뵈르 바게트',price_won='15000',price_dollar='11.85',explanation='Mortadella & artisan butter & baguette',etc='null')
	new_menu=Menu(english_name='Truffle Parma ham baguette',korean_name='트러플 파르마 햄 바게트',price_won='16000',price_dollar='12.64',explanation='Truffle paste & Parma ham & Mozzarella & tomato & arugula & baguette',etc='null')
	new_menu=Menu(english_name='Han-u pattymelt',korean_name='한우 패티멜트',price_won='17000',price_dollar='13.43',explanation='Handmade korean beef patty & caramelized onion & Swiss cheese',etc='null')
	new_menu=Menu(english_name='Han-u cheeseburger',korean_name='한우 치즈버거',price_won='17000',price_dollar='13.43',explanation='Handmade korean beef patty & tomato & Cheddar cheese & lettuce',etc='null')
	new_menu=Menu(english_name='Han-u blue cheeseburger',korean_name='한우 블루 치즈버거',price_won='17000',price_dollar='13.43',explanation='Handmade korean beef patty & caramelized onion & blue cheese',etc='null')
	new_menu=Menu(english_name='Brunch house wine glass red',korean_name='브런치 하우스 와인 글라스 레드',price_won='9000',price_dollar='7.11',explanation='Soft wine',etc='null')
	new_menu=Menu(english_name='Brunch house wine glass white',korean_name='브런치 하우스 와인 글라스 화이트',price_won='9000',price_dollar='7.11',explanation='Dry wine',etc='null')
	new_menu=Menu(english_name='Tomahawk gu-baek gram',korean_name='토마호크 900g',price_won='270000',price_dollar='213.28',explanation='60days dry-aging tomahawk(from USA or AUS) 900g',etc='null')
	new_menu=Menu(english_name='T-bone chil-baek gram',korean_name='T-bone 700g',price_won='260000',price_dollar='205.38',explanation='60days dry-aging T-bone steak(from KOR) 700g',etc='null')
	new_menu=Menu(english_name='Salchi-sal i-baek gram',korean_name='살치살 200g',price_won='89000',price_dollar='70.3',explanation='Chuck flap 200g. 30days aged korean beef 1++ No.9',etc='null')
	new_menu=Menu(english_name='Rump steak i-baek o-sib gram',korean_name='럼(Rump) 스테이크 250g',price_won='44000',price_dollar='34.76',explanation='30days aged korean beef 1++ No.9 250g',etc='null')
	new_menu=Menu(english_name='USDA prime New york strip',korean_name='USDA Prime 뉴욕스트립',price_won='47000',price_dollar='37.13',explanation='Sirloin from USA 250g+',etc='null')
	new_menu=Menu(english_name='Iverico don-hangjeongsal',korean_name='이베리코 돈항정살',price_won='36000',price_dollar='28.44',explanation='Iverian pork jowls 200g',etc='null')
    new_menu=Menu(english_name='I-bun-eui-il roast chicken-gwa yachae-gui',korean_name='1/2 로스트 치킨과 야채구이',price_won='26000',price_dollar='20.54',explanation='Half of roast chicken and grilled veges',etc='null')
	new_menu=Menu(english_name='Ori Confit',korean_name='오리 콩피',price_won='24000',price_dollar='18.96',explanation='Soft duck(KOR) Confit cooked in low-temperature with handmade oil',etc='null')
	new_menu=Menu(english_name='Orange glaze ori gaseumsal gui',korean_name='오렌지 글레이즈 오리 가슴살 구이',price_won='25000',price_dollar='19.75',explanation='Grilled bricket of duck with orange',etc='null')
	new_menu=Menu(english_name='Olive jeol-im',korean_name='올리브 절임',price_won='8000',price_dollar='6.32',explanation='Pickled olive',etc='null')
	new_menu=Menu(english_name='Burrata & tomato salad',korean_name='부라타 & 토마토 샐러드',price_won='18000',price_dollar='14.22',explanation='Tomato salad with Burrata cheese',etc='null')
	new_menu=Menu(english_name='Calamari twigimgwa Ssambal aioli',korean_name='깔라마리 튀김과 Ssambal 아이올리*',price_won='16000',price_dollar='12.64',explanation='Fried calamari with Sambal aioli',etc='null')
	new_menu=Menu(english_name='Softshellcrap twigimgwa ssambal aioli',korean_name='소프트쉘크랩 튀김과 Ssambal 아이올리*',price_won='18000',price_dollar='14.22',explanation='Fried softshell-crap with Sambal aioli',etc='null')
	new_menu=Menu(english_name='Garibi Ceviche',korean_name='가리비 세비채',price_won='17000',price_dollar='13.43',explanation='Raw scallops Ceviche that pickled in citrus',etc='null')
    new_menu=Menu(english_name='Yeon-eo Gravlax on sourdough',korean_name='연어 그라블락스 on 사워도우',price_won='17000',price_dollar='13.43',explanation='Salmon Gravlax on sourdough',etc='null')
	new_menu=Menu(english_name='Dak-gui-wa herbsauce',korean_name='닭(허벅지살)구이와 허브소스',price_won='16000',price_dollar='12.64',explanation='Grilled chicken thigh and herb-sauce',etc='null')
	new_menu=Menu(english_name='Jijunghaesik muneo-guiwa Romesco sauce',korean_name='지중해식 문어구이와 Romesco 소스',price_won='18000',price_dollar='14.22',explanation='Mediterranean grilled octopus & Romesco sauce',etc='null')
	new_menu=Menu(english_name='Sawadikap han-u tartare',korean_name='사와디캅 한우 타르타르',price_won='19000',price_dollar='15.01',explanation='Thai beef(KOR) tartare',etc='null')
	new_menu=Menu(english_name='Han-u bone mero-u, gremolata',korean_name='한우 본 메로우, 그레몰라타',price_won='24000',price_dollar='18.96',explanation='Korean beef bone marrow gremolata',etc='null')
	new_menu=Menu(english_name='Sae-u-sando and Macsauce',korean_name='새우산도와 맥소스',price_won='23000',price_dollar='18.17',explanation='Handmade shrimp & lettuce',etc='null')
	new_menu=Menu(english_name='Meat lovers pizza',korean_name='미트 Lovers 피자 Lunch',price_won='24000',price_dollar='18.96',explanation='Handmade fennel sausage & bacon & ragu sauce & Mozzarella',etc='null')
	new_menu=Menu(english_name='Meat lovers pizza',korean_name='미트 Lovers 피자 Dinner',price_won='25000',price_dollar='19.75',explanation='Handmade fennel sausage & bacon & ragu sauce & Mozzarella',etc='null')
	new_menu=Menu(english_name='Truffle beoseot pizza',korean_name='트러플 버섯 피자',price_won='26000',price_dollar='20.54',explanation='Truffle paste & diverse mushrooms & Mozzarella',etc='null')
	new_menu=Menu(english_name='Margeritta pizza',korean_name='마르게리타 피자(Lunch)',price_won='23000',price_dollar='18.17',explanation='Mozarella & tomato sauce & basil',etc='null')
	new_menu=Menu(english_name='Margeritta pizza',korean_name='마르게리타 피자(Dinner)',price_won='24000',price_dollar='18.96',explanation='Mozarella & tomato sauce & basil',etc='null')
	new_menu=Menu(english_name='Jijunghaesik haesanmul spaghetti',korean_name='지중해식 해산물 스파게티(Lunch)',price_won='23000',price_dollar='18.17',explanation='Mediterranean seafood spaghetti',etc='null')
	
 
 
    new_menu=Menu(english_name='Jijunghaesik haesanmul spaghetti',korean_name='吏�以묓빐�� �댁궛臾� �ㅽ뙆寃뚰떚(Dinner)',price_won='24000',price_dollar='18.96',explanation='Mediterranean seafood spaghetti',etc='null')
	new_menu=Menu(english_name='Myeongran cream talliatelle',korean_name='紐낅� �щ┝ �덈━�꾪깉��',price_won='22000',price_dollar='17.38',explanation='Tagliatelle with roe of pollock cream',etc='null')
	new_menu=Menu(english_name='Han-u Bolognese spaghetti',korean_name='�쒖슦 蹂쇰줈�ㅼ젣 �ㅽ뙆寃뚰떚(Lunch)',price_won='16000',price_dollar='12.64',explanation='Bolognese spaghetti with korean beef',etc='null')
	new_menu=Menu(english_name='Han-u Bolognese spaghetti',korean_name='�쒖슦 蹂쇰줈�ㅼ젣 �ㅽ뙆寃뚰떚(Dinner)',price_won='17000',price_dollar='13.43',explanation='Bolognese spaghetti with korean beef',etc='null')
	new_menu=Menu(english_name='Peurangseu-sik han-u ragu spaghetti',korean_name='�꾨옉�ㅼ떇 �쒖슦 �쇨뎄 �ㅽ뙆寃뚰떚',price_won='23000',price_dollar='18.17',explanation='French ragu spaghetti with korean beef',etc='null')
	new_menu=Menu(english_name='Sweet corn beosut Carbonara',korean_name='�ㅼ쐞�� 肄� 踰꾩꽢 源뚮Ⅴ蹂대굹��',price_won='18000',price_dollar='14.22',explanation='Mushroom Carbonara with sweet corns',etc='null')
	new_menu=Menu(english_name='Artisan cheese sam-jong plate',korean_name='�꾪떚�� 移섏쫰 3醫� �뚮젅�댄듃',price_won='18000',price_dollar='14.22',explanation='',etc='null')
	new_menu=Menu(english_name='Prosciutto, italian pickle, showerdough',korean_name='�꾨줈�덈삉, �댄깉由ъ븞 �쇳겢, �ㅼ썙 �꾩슦',price_won='14000',price_dollar='11.06',explanation='Prosciutto & italian pickle & shower dough',etc='null')
	new_menu=Menu(english_name='Mortadella, italian pickle, showerdough',korean_name='紐⑦��먮씪, �댄깉由ъ븞 �쇳겢, �ㅼ썙 �꾩슦',price_won='13000',price_dollar='10.27',explanation='Mortadella, italian pickle & shower dough',etc='null')
	new_menu=Menu(english_name='Beoseot-Mascarpone-cheese-Omeulet brunch',korean_name='踰꾩꽢留덉뒪移댄룷�ㅼ튂利덉삤誘덈젢 釉뚮윴移�',price_won='16000',price_dollar='12.64',explanation='Mushroom Mascarpone cheese Omelet & french toast & fried potatoes & bacon sausage & Cobb salad',etc='null')
	new_menu=Menu(english_name='Gyejeol-gwail french toast',korean_name='怨꾩젅怨쇱씪�꾨젋移섑넗�ㅽ듃',price_won='14000',price_dollar='11.06',explanation='French toast with maple syrup, cream & seasonal fruit',etc='null')
	new_menu=Menu(english_name='Pepperoni ragu Omeulet brunch',korean_name='�섑띁濡쒕땲�쇨뎄�ㅻ칷�� 釉뚮윴移�',price_won='16000',price_dollar='12.64',explanation='Pepperoni ragu Omelet & french toast & fried potatoes & bacon sausage & Cobb salad',etc='null')
	new_menu=Menu(english_name='Sae-u cream pasta',korean_name='�덉슦�щ┝�뚯뒪��',price_won='14000',price_dollar='11.06',explanation='Cream pasta with shrimp & bacon, baguette',etc='null')
	new_menu=Menu(english_name='Amatriciana',korean_name='�꾨쭏�몃━移섏븘��',price_won='14500',price_dollar='11.45',explanation='Amatriciana pasta',etc='null')
	new_menu=Menu(english_name='Classic Omeulet brunch',korean_name='�대옒�� �ㅻ칷�� 釉뚮윴移�',price_won='16000',price_dollar='12.64',explanation='Omelet & French toast & fried potatoes & bacon sausage & Cobb salad',etc='null')
	new_menu=Menu(english_name='Egg scramble brunch',korean_name='�먭렇 �ㅽ겕�⑤툝 釉뚮윴移�',price_won='13500',price_dollar='10.66',explanation='Scrambled egg & french toast & fried potatoes & Cobb salad & bacon sausage',etc='null')
	new_menu=Menu(english_name='Sae-u green salad',korean_name='�덉슦洹몃┛ �먮윭��',price_won='14500',price_dollar='11.45',explanation='Salad with shrimps, dressing & baguette 2 pieces',etc='null')
	new_menu=Menu(english_name='Ricotta cheese salad',korean_name='由ъ퐫�� 移섏쫰 �먮윭��',price_won='14000',price_dollar='11.06',explanation='Salad with Ricotta cheese, dressing & baguette 2 pieces',etc='null')
	new_menu=Menu(english_name='Lasagna',korean_name='�쇱옄��',price_won='16000',price_dollar='12.64',explanation='',etc='null')
	new_menu=Menu(english_name='Mushroom cream pasta',korean_name='癒몄돩猷� �щ┝ �뚯뒪��',price_won='14500',price_dollar='11.45',explanation='Mushroom cream pasta with baguette',etc='null')
	new_menu=Menu(english_name='Yeon-eo cream risotto',korean_name='�곗뼱 �щ┝ 由ъ“��',price_won='17000',price_dollar='13.43',explanation='Salmon steak & truffle oiled cream risotto',etc='null')
	new_menu=Menu(english_name='Vongole',korean_name='遊됯낏��',price_won='15000',price_dollar='11.85',explanation='Vongole pasta with baguette',etc='null')
	new_menu=Menu(english_name='Sae-u ros챕 pasta',korean_name='�덉슦 濡쒖젣 �뚯뒪��',price_won='14500',price_dollar='11.45',explanation='Ros챕 pasta with shrimp & bread',etc='null')
	new_menu=Menu(english_name='Aglio olio',korean_name='�뚮━�� �щ━��',price_won='13500',price_dollar='10.66',explanation='Aglio olio pasta with garlic & bread',etc='null')
	new_menu=Menu(english_name='Ice americano',korean_name='�꾩씠�� �꾨찓由ъ뭅��',price_won='3000',price_dollar='2.37',explanation='',etc='null')
	new_menu=Menu(english_name='Americano',korean_name='�꾨찓由ъ뭅��',price_won='3000',price_dollar='2.37',explanation='',etc='null')
	new_menu=Menu(english_name='Ice latte',korean_name='�꾩씠�� �쇰뼹',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe latte',korean_name='移댄럹 �쇰뼹',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Ice milk tea',korean_name='�꾩씠�� 諛��ы떚',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='milk tea',korean_name='諛��ы떚',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Ice vanilla latte',korean_name='�꾩씠�� 諛붾땺�� �쇰뼹',price_won='5500',price_dollar='4.34',explanation='',etc='null')
	new_menu=Menu(english_name='Vanilla latte',korean_name='諛붾땺�� �쇰뼹',price_won='5500',price_dollar='4.34',explanation='',etc='null')
	new_menu=Menu(english_name='Ice choco latte',korean_name='�꾩씠�� 珥덉퐫�쇰뼹',price_won='5500',price_dollar='4.34',explanation='',etc='null')
	new_menu=Menu(english_name='Choco latte',korean_name='珥덉퐫�쇰뼹',price_won='5500',price_dollar='4.34',explanation='',etc='null')
	new_menu=Menu(english_name='Jamong-ade',korean_name='�먮そ�먯씠��',price_won='6500',price_dollar='5.13',explanation='Grapefruit-ade',etc='null')
	new_menu=Menu(english_name='Lemonade',korean_name='�덈が�먯씠��',price_won='6500',price_dollar='5.13',explanation='',etc='null')
	new_menu=Menu(english_name='Wine-cocktail',korean_name='���몄뭇�뚯씪',price_won='4000',price_dollar='3.16',explanation='Cocktail of red-wine & white-wine',etc='null')
	new_menu=Menu(english_name='Cream-cheese gwa-il salad',korean_name='�щ┝移섏쫰 怨쇱씪 �먮윭��',price_won='16000',price_dollar='12.64',explanation='Fruit salad with cream cheese',etc='null')
	new_menu=Menu(english_name='Tong romaine bacon salad',korean_name='�듬줈硫붿씤踰좎씠而� �먮윭��',price_won='17000',price_dollar='13.43',explanation='Romaine bacon salad with dressing sauce',etc='null')
	new_menu=Menu(english_name='Butter-cream sae-u',korean_name='踰꾪꽣�щ┝�덉슦',price_won='15000',price_dollar='11.85',explanation='Shrimp with butter cream & bread',etc='null')
	new_menu=Menu(english_name='Grana-padano pepper',korean_name='洹몃씪�섑뙆�ㅻ끂�섑띁',price_won='17000',price_dollar='13.43',explanation='Oiled pepper spaghetti with Grana padano cheese',etc='null')
	new_menu=Menu(english_name='Seu-tab mil pasta',korean_name='�ㅽ꺆諛��뚯뒪��',price_won='21000',price_dollar='16.59',explanation='Spicy tomato sauce spaghetti with bacon & shrimp(originated from staff meal)',etc='null')
	new_menu=Menu(english_name='Shrimp jambal-raya',korean_name='�щ┝�� �좊컻�쇱빞',price_won='22000',price_dollar='17.38',explanation='Bit spicy Jambalaya with cream sauce & cheese shrimp',etc='null')
	new_menu=Menu(english_name='Shrimp rucola Ros챕 pasta',korean_name='�щ┝�� 猷④섦�� 濡쒖젣 �뚯뒪��',price_won='24000',price_dollar='18.96',explanation='Ros챕 spaghetti with black-tiger shrimp & arugula & cheese',etc='null')
	new_menu=Menu(english_name='Chicken Bureu-seu-geta',korean_name='移섑궓 遺�瑜댁뒪寃뚰�',price_won='22000',price_dollar='17.38',explanation='3 kinds of cheese & 3 kinds of veges & 3 kinds of sauce with tender chicken on bread',etc='null')
	new_menu=Menu(english_name='Beolkkul danhobak pasta',korean_name='踰뚭� �⑦샇諛� �뚯뒪��',price_won='22000',price_dollar='17.38',explanation='Whole-bacon and arugula honey-bread with pumpkin-cream on pasta',etc='null')
	new_menu=Menu(english_name='Burrata cheese-wa Arabiatta pasta',korean_name='遺��쇳� 移섏쫰�� �꾨씪鍮꾩븘�� �뚯뒪��',price_won='25000',price_dollar='19.75',explanation='Arrabbiata pasta with Burrata cheese',etc='null')
	new_menu=Menu(english_name='Truffle gnocchi',korean_name='�몃윭�� �⑤겮',price_won='27000',price_dollar='21.33',explanation='Gnocchi with Truffle cream sauce and cheese & mushrooms',etc='null')
	new_menu=Menu(english_name='Shrimp-kkasuel-ra',korean_name='�щ┝�꾧퉴�섏뿕��',price_won='25000',price_dollar='19.75',explanation='Grilled shrimp and bread by olive oil',etc='null')
	new_menu=Menu(english_name='French toast-wa coffee',korean_name='�꾨젋移� �좎뒪�몄� 而ㅽ뵾',price_won='15000',price_dollar='11.85',explanation='French toast with coffee',etc='null')
	new_menu=Menu(english_name='Englsih breakfast-wa coffee',korean_name='�됯�由ъ돩 釉붾옓�쇱뒪�몄� 而ㅽ뵾',price_won='15000',price_dollar='11.85',explanation='English breakfast with coffee',etc='null')
	new_menu=Menu(english_name='Burrata cheese-wa Jeol-im bang-ul tomato',korean_name='遺��쇳�移섏쫰�� �덉엫 諛⑹슱�좊쭏��',price_won='18000',price_dollar='14.22',explanation='Pickled cherry tomatoes with Burrata cheese',etc='null')
	new_menu=Menu(english_name='Mojito',korean_name='紐⑦엳��',price_won='12000',price_dollar='9.48',explanation='Mojito with mixture option(musket/orange/grapefruit/lemon)',etc='null')
	new_menu=Menu(english_name='Non-alkol mohito',korean_name='�� �뚯퐳 紐⑦엳��',price_won='9500',price_dollar='7.5',explanation='Non-alcohol mojito',etc='null')
	new_menu=Menu(english_name='Cheongpodo ade',korean_name='泥�룷�� �먯씠��',price_won='7500',price_dollar='5.92',explanation='Musket-ade',etc='null')
	new_menu=Menu(english_name='Orange ade',korean_name='�ㅻ젋吏� �먯씠��',price_won='7500',price_dollar='5.92',explanation='',etc='null')
	new_menu=Menu(english_name='Jamong ade',korean_name='�먮そ �먯씠��',price_won='7500',price_dollar='5.92',explanation='Grapefruit-ade',etc='null')
	new_menu=Menu(english_name='Lemonade',korean_name='�덈が �먯씠��',price_won='7500',price_dollar='5.92',explanation='',etc='null')
	new_menu=Menu(english_name='Yuja ade',korean_name='�좎옄 �먯씠��',price_won='7500',price_dollar='5.92',explanation='Citrus ade',etc='null')
	new_menu=Menu(english_name='Orange juice',korean_name='�ㅻ젋吏� 二쇱뒪',price_won='8000',price_dollar='6.32',explanation='',etc='null')
	new_menu=Menu(english_name='Jamong juice',korean_name='�먮そ 二쇱뒪',price_won='8000',price_dollar='6.32',explanation='Grapefruit juice',etc='null')
	new_menu=Menu(english_name='Orange en jamong juice',korean_name='�ㅻ젋吏� & �먮そ 二쇱뒪',price_won='8000',price_dollar='6.32',explanation='Orange & grapefruit juice',etc='null')
	new_menu=Menu(english_name='Americano',korean_name='�꾨찓由ъ뭅��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe latte',korean_name='移댄럹 �쇰뼹',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Vanilla latte',korean_name='諛붾땺�� �쇰뼹',price_won='6500',price_dollar='5.13',explanation='',etc='null')
	new_menu=Menu(english_name='Yeon-yu latte',korean_name='�곗쑀�쇰뼹',price_won='6500',price_dollar='5.13',explanation='Latte with condensed milk',etc='null')
	new_menu=Menu(english_name='So-geum coffee',korean_name='�뚭툑而ㅽ뵾',price_won='7500',price_dollar='5.92',explanation='Sea salt coffee',etc='null')
	new_menu=Menu(english_name='So-geum gui i-baek gram',korean_name='�뚭툑援ъ씠 200g',price_won='13000',price_dollar='10.27',explanation='Salt-grilled pork 200g',etc='null')
	new_menu=Menu(english_name='Samgyeopsal i-baek gram',korean_name='�쇨껸�� 200g',price_won='13000',price_dollar='10.27',explanation='Pork belly 200g',etc='null')
	new_menu=Menu(english_name='So-galbisal i-baek gram',korean_name='�뚭컝鍮꾩궡 200g',price_won='17000',price_dollar='13.43',explanation='Grilled boneless beef ribs 200g',etc='null')
	new_menu=Menu(english_name='Chadol-bagi i-baek gram',korean_name='李⑤룎諛뺤씠 200g',price_won='16000',price_dollar='12.64',explanation='Beef brisket 200g',etc='null')
	new_menu=Menu(english_name='Hangjeongsal i-baek gram',korean_name='��젙�� 200g',price_won='13000',price_dollar='10.27',explanation='Grilled pork neck 200g',etc='null')
	new_menu=Menu(english_name='Galmaegisal i-baek gram',korean_name='媛덈ℓ湲곗궡 200g',price_won='13000',price_dollar='10.27',explanation='Korean pork skirt 200g',etc='null')
	new_menu=Menu(english_name='Dwaeji-makchang i-baek gram',korean_name='�쇱�留됱갹 200g',price_won='13000',price_dollar='10.27',explanation='Grilled pork tripe 200g',etc='null')
	new_menu=Menu(english_name='Dwaji-galbi i-baek gram',korean_name='�쇱�媛덈퉬 200g',price_won='13000',price_dollar='10.27',explanation='Grilled pork ribs 200g',etc='null')
	new_menu=Menu(english_name='Samgyeopsal baekpalsib gram',korean_name='�쇨껸��(180g)',price_won='15000',price_dollar='11.85',explanation='Pork belly(180g)',etc='null')
	new_menu=Menu(english_name='Almoksal baekpalsib gram',korean_name='�뚮ぉ��(180g)',price_won='15000',price_dollar='11.85',explanation='Grilled pork shoulder(180g)',etc='null')
	new_menu=Menu(english_name='Doraechang bok-eum i-baek gram',korean_name='�꾨옒李쎈낭��(200g)*',price_won='15000',price_dollar='11.85',explanation='Stir-fried pork special part(muscle membrane?)',etc='null')
	new_menu=Menu(english_name='Myeong-in-eui doenjang-jjigae',korean_name='紐낆씤�� �쒖옣李뚭컻',price_won='5000',price_dollar='3.95',explanation='Korean soybean paste jjigae(Signature)',etc='null')
	new_menu=Menu(english_name='Bok-eum bap',korean_name='蹂띠쓬諛�',price_won='4000',price_dollar='3.16',explanation='Fried rice',etc='null')
	new_menu=Menu(english_name='U-reong doenjang sotbab',korean_name='�곕쟻�쒖옣�λ갈',price_won='6000',price_dollar='4.74',explanation='Pot rice with korean soy bean paste & freshwater snail',etc='null')
	new_menu=Menu(english_name='Aehobak bajirak dwaeji jjigae',korean_name='�좏샇諛� 諛붿��� �쇱�李뚭컻',price_won='6000',price_dollar='4.74',explanation='Korean pork jjigae with clams & zucchini',etc='null')
	new_menu=Menu(english_name='Jaechub Oilpasta',korean_name='�ъ꺽 �ㅼ씪�뚯뒪��',price_won='6000',price_dollar='4.74',explanation='Oil pasta with marsh clams',etc='null')
	new_menu=Menu(english_name='Jaechub guksu',korean_name='�ъ꺽援�닔',price_won='6000',price_dollar='4.74',explanation='Korean noodle with marsh clams',etc='null')
	new_menu=Menu(english_name='Geubraeng samgyeopsal',korean_name='湲됰옲�쇨껸��',price_won='12000',price_dollar='9.48',explanation='Frozen pork belly with special Sioyaki sauce',etc='null')
	new_menu=Menu(english_name='Jeju heukdwaji kkodeulsal',korean_name='�쒖＜�묐뤌吏� 瑗щ뱾��*',price_won='13000',price_dollar='10.27',explanation='Grilled Jeju black pork shoulder',etc='null')
	new_menu=Menu(english_name='Saeng samgyeopsal',korean_name='�앹궪寃뱀궡',price_won='14000',price_dollar='11.06',explanation='Pork belly',etc='null')
	new_menu=Menu(english_name='Handon gogi-modeum',korean_name='�쒕룉 怨좉린紐⑤몺',price_won='51900',price_dollar='41',explanation='Korean pork belly 150g & korean pork shoulder 300g & korean pork skirt + korean soy bean paste jjigae',etc='null')
	new_menu=Menu(english_name='Handon tongmoksal',korean_name='�쒕룉 �듬ぉ��',price_won='13900',price_dollar='10.98',explanation='Korean pork shoulder',etc='null')
	new_menu=Menu(english_name='Han-u gopchangmodeum i-in',korean_name='�쒖슦 怨깆갹紐⑤몺 2��',price_won='39900',price_dollar='31.52',explanation='Korean beef small intestines set & korean soy bean paste jjigae',etc='null')
	new_menu=Menu(english_name='Han-u sogobchang',korean_name='�쒖슦 �뚭낢李�',price_won='19900',price_dollar='15.72',explanation='Korean beef small intestines',etc='null')
	new_menu=Menu(english_name='Han-u Kalsamgyeop',korean_name='�쒖슦 移쇱궪寃�',price_won='13900',price_dollar='10.98',explanation='Korean scored beef belly',etc='null')
	new_menu=Menu(english_name='Handon galmaegisal',korean_name='�쒕룉 媛덈ℓ湲곗궡',price_won='13900',price_dollar='10.98',explanation='Korean pork skirt',etc='null')
	new_menu=Menu(english_name='Han-u sodaechang',korean_name='�쒖슦 �뚮�李�',price_won='18900',price_dollar='14.93',explanation='Korean beef large intestines',etc='null')
	new_menu=Menu(english_name='U-dae galbi',korean_name='�곕�媛덈퉬*',price_won='27000',price_dollar='21.33',explanation='Korean beef large ribs?',etc='null')
	new_menu=Menu(english_name='Sogalbisal',korean_name='�뚭컝鍮꾩궡',price_won='17000',price_dollar='13.43',explanation='Korean beef ribs',etc='null')
	new_menu=Menu(english_name='Beoljip kkeopdegi',korean_name='踰뚯쭛猿띾뜲湲�*',price_won='8000',price_dollar='6.32',explanation='Grilled comb cut pork rinds',etc='null')
	new_menu=Menu(english_name='Americano',korean_name='�꾨찓由ъ뭅��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe Latte',korean_name='移댄럹�쇰뼹',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Vanilla Latte',korean_name='諛붾땺�쇰씪��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='flat white',korean_name='�뚮옯 �붿씠��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe vienna',korean_name='移댄럹 鍮꾩뿏��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='McCoy Coffee',korean_name='留μ퐫�� 而ㅽ뵾',price_won='6000',price_dollar='4.74',explanation='Signature roasting coffee',etc='null')
	new_menu=Menu(english_name='Cafe Espresso',korean_name='移댄럹 �먯뒪�꾨젅��',price_won='4000',price_dollar='3.16',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe con panna',korean_name='移댄럹 肄� �먮굹',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe Chocolat',korean_name='移댄럹 �쇱퐳��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe bongbong',korean_name='移댄럹 遊됰큺',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe Affogato',korean_name='移댄럹 �꾪룷媛���',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe Shakerato',korean_name='移댄럹 �ㅼ��쇳넗',price_won='7000',price_dollar='5.53',explanation='',etc='null')
	new_menu=Menu(english_name='Filter coffee',korean_name='�꾪꽣 而ㅽ뵾',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Yung coffee',korean_name='�� 而ㅽ뵾',price_won='9000',price_dollar='7.11',explanation='',etc='null')
	new_menu=Menu(english_name='Chocolate latte',korean_name='珥덉퐫�쇰뼹',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Ttalgi latte',korean_name='�멸린�쇰뼹',price_won='6000',price_dollar='4.74',explanation='Strawberry Latte',etc='null')
	new_menu=Menu(english_name='Missu latte',korean_name='誘몄닽�쇰뼹',price_won='6000',price_dollar='4.74',explanation='Mixed grain powder latte',etc='null')
	new_menu=Menu(english_name='Lemonade',korean_name='�덈が �먯씠��',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Financier',korean_name='�섎궘�쒖뿉',price_won='2500',price_dollar='1.98',explanation='',etc='null')
	new_menu=Menu(english_name='Tiramisu',korean_name='�곕씪誘몄닔',price_won='7000',price_dollar='5.53',explanation='',etc='null')
	new_menu=Menu(english_name='Ttalgi Tiramisu',korean_name='�멸린 �곕씪誘몄닔',price_won='8000',price_dollar='6.33',explanation='Tiramisu with strawberry',etc='null')
	new_menu=Menu(english_name='Americano',korean_name='�꾨찓由ъ뭅��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Cafe Latte',korean_name='移댄럹�쇰뼹',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Cappuccino (only Hot)',korean_name='移댄뫖移섎끂(only Hot)',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Vanilla Latte',korean_name='諛붾땺�쇰씪��',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Caramel Latte',korean_name='移대씪硫쒕씪��',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Butter Cream Latte (only Ice)',korean_name='踰꾪꽣�щ┝�쇰뼹(only Ice)',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Einspanner',korean_name='�꾩씤�덊럹��',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Cream milk tea',korean_name='�щ┝諛��ы떚',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Matcha milk',korean_name='留먯감諛���',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Wedding imperial',korean_name='�⑤뵫�꾪럹由ъ뼹',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Hibiscus Lemon',korean_name='�덈퉬�ㅼ빱�ㅻ젅紐�',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Chamomile',korean_name='罹먮え留덉씪',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Rooibos Vanilla',korean_name='猷⑥씠蹂댁뒪諛붾땺��',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Lemon&Berry Ade',korean_name='�덈が踰좊━�먯씠��',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Cheongpodo-ade',korean_name='泥�룷�꾩뿉�대뱶',price_won='7000',price_dollar='5.54',explanation='Green Grape Ade',etc='null')
	new_menu=Menu(english_name='Jamong-ade',korean_name='�먮そ�먯씠��',price_won='7000',price_dollar='5.54',explanation='Grapefruit Ade',etc='null')
	new_menu=Menu(english_name='Tropical Ade',korean_name='�몃줈�쇱뺄�먯씠��',price_won='7000',price_dollar='5.54',explanation='Tropical Ade',etc='null')
	new_menu=Menu(english_name='Drip coffee',korean_name='�쒕┰而ㅽ뵾',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Mocha pot Coffee',korean_name='紐⑥뭅�ы듃而ㅽ뵾',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Mocha pot Latte',korean_name='紐⑥뭅�ы듃 �쇰뼹',price_won='8000',price_dollar='6.33',explanation='',etc='null')
	new_menu=Menu(english_name='Cold Brew',korean_name='肄쒕뱶釉뚮（ 而ㅽ뵾',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Cold Brew Latte',korean_name='肄쒕뱶釉뚮（ �쇰뼹',price_won='8000',price_dollar='6.33',explanation='',etc='null')
	new_menu=Menu(english_name='Green Tea',korean_name='�섏쫰',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='White Tea',korean_name='�붿씠�� �섑깉',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Black Tea',korean_name='濡쒕뱶踰좊Ⅴ媛�紐�',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Lemon Tea(HOT)',korean_name='�덈が��',price_won='7000',price_dollar='5.54',explanation='',etc='null')
	new_menu=Menu(english_name='Cacao Milk',korean_name='移댁뭅�ㅻ���',price_won='9000',price_dollar='7.12',explanation='',etc='null')
	new_menu=Menu(english_name='Matcha Milk',korean_name='留먯감 諛���',price_won='9000',price_dollar='7.12',explanation='',etc='null')
	new_menu=Menu(english_name='Passionfruit ade',korean_name='�⑥뀡�꾨Ⅴ痢� �먯씠��',price_won='9000',price_dollar='7.12',explanation='',etc='null')
	new_menu=Menu(english_name='Lemonade',korean_name='�덈が �먯씠��',price_won='9000',price_dollar='7.12',explanation='',etc='null')
	new_menu=Menu(english_name='Chai Milk',korean_name='李⑥씠 諛���',price_won='9000',price_dollar='7.12',explanation='',etc='null')
	new_menu=Menu(english_name='Espresso',korean_name='�먯냼�꾨젅��',price_won='5000',price_dollar='3.96',explanation='',etc='null')
	new_menu=Menu(english_name='Americano',korean_name='�꾨찓由ъ뭅��',price_won='5000',price_dollar='3.96',explanation='',etc='null')
	new_menu=Menu(english_name='Vienna',korean_name='鍮꾩뿏��',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Flat White',korean_name='�뚮옯�붿씠��',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Latte',korean_name='�쇰뼹',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Vanilla Latte',korean_name='諛붾땺�쇰씪��',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Deep Mocha',korean_name='�� 紐⑥뭅',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Mandarin Ade',korean_name='留뚮떎由곗뿉�대뱶',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='57% Cacao',korean_name='57% 移댁뭅��',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Jardin Blue',korean_name='�먮럢釉붾（',price_won='6000',price_dollar='4.75',explanation='Signature black tea',etc='null')
	new_menu=Menu(english_name='Ceylan O.P.',korean_name='�ㅻ줎 O.P',price_won='6000',price_dollar='4.75',explanation='',etc='null')
	new_menu=Menu(english_name='Camomille',korean_name='罹먮え留덉씪',price_won='6000',price_dollar='4.75',explanation='',etc='null')
	new_menu=Menu(english_name='White Fleurs',korean_name='�붿씠�� �뚮젅瑜�',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Ethiopia',korean_name='�먰떚�ㅽ뵾��',price_won='7000',price_dollar='5.53',explanation='',etc='null')
	new_menu=Menu(english_name='SUNSET',korean_name='SUNSET',price_won='7000',price_dollar='5.53',explanation='',etc='null')
	new_menu=Menu(english_name='Columbia',korean_name='肄쒕＼鍮꾩븘',price_won='7500',price_dollar='5.93',explanation='',etc='null')
	new_menu=Menu(english_name='"Kenya x Keya"',korean_name='耳��륺耳���',price_won='7500',price_dollar='5.93',explanation='',etc='null')
	new_menu=Menu(english_name='Black Suit',korean_name='釉붾옓�섑듃',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Velvet white',korean_name='踰⑤껙�붿씠��',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Malt',korean_name='紐고듃',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='Espresso',korean_name='�먯냼�꾨젅��',price_won='5000',price_dollar='3.95',explanation='',etc='null')
	new_menu=Menu(english_name='Americano',korean_name='�꾨찓由ъ뭅��',price_won='5500',price_dollar='4.35',explanation='',etc='null')
	new_menu=Menu(english_name='Latte',korean_name='�쇰뼹',price_won='6300',price_dollar='4.98',explanation='',etc='null')
	new_menu=Menu(english_name='Cappuccino',korean_name='移댄뫖移섎끂',price_won='6300',price_dollar='4.98',explanation='',etc='null')
	new_menu=Menu(english_name='Barista Special',korean_name='諛붾━�ㅽ��ㅽ럹��',price_won='8000',price_dollar='6.33',explanation='',etc='null')
	new_menu=Menu(english_name='Cold brew',korean_name='肄쒕뱶釉뚮（',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Seasonal coffee',korean_name='�쒖쫰�� 而ㅽ뵾',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Real caramel',korean_name='由ъ뼹 移대씪硫�',price_won='6500',price_dollar='5.14',explanation='',etc='null')
	new_menu=Menu(english_name='Real fruit',korean_name='由ъ뼹 �꾨（痢�',price_won='7000',price_dollar='5.53',explanation='',etc='null')
	new_menu=Menu(english_name='Matgimcharim',korean_name='留↔�李⑤┝(1�몄슜)',price_won='45000',price_dollar='35.57',explanation='Korean course set that made of seasonal Jiri-mountain foods (served as Omakase) for 1 person',etc='null')
	new_menu=Menu(english_name='Dam-eun',korean_name='�댁�',price_won='24000',price_dollar='18.97',explanation='Korean Unrefined Rice Wine brand',etc='null')
	new_menu=Menu(english_name='Kkot-jam',korean_name='苑껋옞',price_won='27000',price_dollar='21.34',explanation='Korean Unrefined Rice Wine brand',etc='null')
	new_menu=Menu(english_name='Oneul-eui makgulri',korean_name='�ㅻ뒛�� 留됯구由� 3��',price_won='15000',price_dollar='11.86',explanation='Daily set consisted of 3 cups of Korean Unrefined Rice Wine',etc='null')
	new_menu=Menu(english_name='Natural wine',korean_name='�댁텛�댁���',price_won='Notfixed',price_dollar='Notfixed',explanation='Various natural wine',etc='null')
	new_menu=Menu(english_name='Lunch-hanjeong hotdog',korean_name='�곗튂�쒖젙 Hotdog',price_won='6900',price_dollar='5.45',explanation='Hotdog only for lunch(3 option : lamb ragu hotdog, sweet corn hotdog, truffle egg hotdog)',etc='null')
	new_menu=Menu(english_name='Ragu pasta',korean_name='�쇨뎄 �뚯뒪��',price_won='19000',price_dollar='15.02',explanation='',etc='null')
	new_menu=Menu(english_name='Hanchi',korean_name='�쒖튂',price_won='20000',price_dollar='15.81',explanation='Calalmari',etc='null')
	new_menu=Menu(english_name='Spainsik gamja-twigim',korean_name='�ㅽ럹�몄떇 媛먯옄��源�',price_won='10000',price_dollar='7.91',explanation='Spanish fried potatoes(middle size)',etc='null')
	new_menu=Menu(english_name='Gaji',korean_name='媛�吏�',price_won='12000',price_dollar='9.49',explanation='Egg plants cuisine with cashewnut, mascapone cheese',etc='null')
	new_menu=Menu(english_name='Spare rib',korean_name='�ㅽ럹�대┰',price_won='25000',price_dollar='19.76',explanation='',etc='null')
	new_menu=Menu(english_name='Iberico pork steak',korean_name='�대쿋由ъ퐫 �ㅽ뀒�댄겕',price_won='29000',price_dollar='22.93',explanation='',etc='null')
	new_menu=Menu(english_name='Sweetcorn',korean_name='�ㅼ쐞�몄퐯',price_won='6900',price_dollar='5.45',explanation='',etc='null')
	new_menu=Menu(english_name='Yang-gogi ragu',korean_name='�묎퀬湲� �쇨뎄',price_won='7900',price_dollar='6.25',explanation='Lamb cuisine with ragu sauce',etc='null')
	new_menu=Menu(english_name='Truffle egg',korean_name='�몃윭�� �먭렇',price_won='7900',price_dollar='6.25',explanation='',etc='null')
	new_menu=Menu(english_name='Coleslaw',korean_name='肄붿슱�щ줈',price_won='4000',price_dollar='3.16',explanation='',etc='null')
	new_menu=Menu(english_name='Spainsik gamja-twigim',korean_name='�ㅽ럹�몄떇 媛먯옄��源�',price_won='8000',price_dollar='6.32',explanation='Spanish fried potatoes(small size)',etc='null')
	new_menu=Menu(english_name='Meoktae',korean_name='癒뱁깭',price_won='18000',price_dollar='14.23',explanation='Grilled Dried Pollack that teared by hand',etc='null')
	new_menu=Menu(english_name='Saengmaekju',korean_name='�앸㎘二�',price_won='5000',price_dollar='3.95',explanation='Draft Beer',etc='null')
	new_menu=Menu(english_name='Caprese salad',korean_name='移댄봽�덉젣 �먮윭��',price_won='15000',price_dollar='11.86',explanation='',etc='null')
	new_menu=Menu(english_name='Suje sausage-wa Modum Yachaegui',korean_name='�섏젣�뚯떆吏��� 紐⑤벉�쇱콈援ъ씠',price_won='20000',price_dollar='15.81',explanation='Handmade sausage with grilled assorted vegetables',etc='null')
	new_menu=Menu(english_name='Gambasalahiyo',korean_name='媛먮컮�� �� �꾪엳��',price_won='23000',price_dollar='18.18',explanation='Gambas al Ajillo (Spanish Garlic Shrimp)',etc='null')
	new_menu=Menu(english_name='Golbaengimuchimgwa somyeon',korean_name='怨⑤콉�대Т移④낵 �뚮㈃',price_won='18000',price_dollar='14.23',explanation='Spicy Sea Snail Salad with Noodles',etc='null')
	new_menu=Menu(english_name='Gaji-tomato-cheese oven gui',korean_name='媛�吏��좊쭏�좎튂利덉삤釉먭뎄��',price_won='18000',price_dollar='14.23',explanation='Oven-baked egg plants & tomato with cheese added',etc='null')
	new_menu=Menu(english_name='Cheese plate',korean_name='移섏쫰�뚮젅�댄듃',price_won='22000',price_dollar='17.39',explanation='Cheese & biscuits with olive and some fruits',etc='null')
	new_menu=Menu(english_name='Brie cheese gui',korean_name='釉뚮━移섏쫰援ъ씠',price_won='15000',price_dollar='11.86',explanation='Grilled Brie cheese',etc='null')
	new_menu=Menu(english_name='Kingdom',korean_name='Kingdom',price_won='20000',price_dollar='15.81',explanation='Lee Gang Ju, Lemon Juice, Basil, Pear Juice, Sugar Syrup',etc='null')
	new_menu=Menu(english_name='South bramble',korean_name='South bramble',price_won='21000',price_dollar='16.6',explanation='Gin, Cassis, Lemon Juice, Raspberry Wine',etc='null')
	new_menu=Menu(english_name='Blue grape',korean_name='Blue grape',price_won='21000',price_dollar='16.6',explanation='Vodka, White Wine, Grapefruit Liqueur, Herb Grape Cordial, Tonic Water',etc='null')
	new_menu=Menu(english_name='SNC Mule',korean_name='SNC Mule',price_won='22000',price_dollar='17.39',explanation='Vodka, Lime Juice, Homemade Ginger Beer, Angostura Bitter',etc='null')
	new_menu=Menu(english_name='K punch',korean_name='K punch',price_won='22000',price_dollar='17.39',explanation='Cognac, Korean Rice Wine, Lemon Juice, Muscat Liqueur, Schisandra, Grenadine Syrup',etc='null')
	new_menu=Menu(english_name='Islay negroni',korean_name='Islay negroni',price_won='26000',price_dollar='20.55',explanation='Gin, Campari, Sweet Vermouth, Plum Sake, Islay Whisky, Angostura Bitter',etc='null')
	new_menu=Menu(english_name='23 Daiquri',korean_name='23 Daiquri',price_won='28000',price_dollar='22.13',explanation='Dark Rum, Mint, Cacao Liqueur, Lime Juice, Smoke Tea Syrup',etc='null')
	new_menu=Menu(english_name='Peach sweet',korean_name='Peach sweet',price_won='28000',price_dollar='22.13',explanation='Vodka, White Peach Juice, Passion Fruit Puree, Vanilla Syrup, Lime Juice, Sparkling Wine',etc='null')
	new_menu=Menu(english_name='Nut-dakgangjeong',korean_name='�덊듃��컯��',price_won='16900',price_dollar='13.36',explanation='Glazed Fried Chicken Bites with nuts',etc='null')
	new_menu=Menu(english_name='Garaage twigim',korean_name='媛��쇱븘寃뚰�源�',price_won='16900',price_dollar='13.36',explanation='Deep-fried Chicken',etc='null')
	new_menu=Menu(english_name='Chickenbaeng-i muchim',korean_name='移섑궓諭낆씠臾댁묠',price_won='18900',price_dollar='14.94',explanation='Sea Snail Salad with chicken',etc='null')
	new_menu=Menu(english_name='Buffalo mat dakbong',korean_name='踰꾪뙏濡쒕쭧��큺',price_won='16900',price_dollar='13.36',explanation='Chicken Drumsticks with buffalo sauce',etc='null')
	new_menu=Menu(english_name='Saewu twigim',korean_name='�덉슦��源�',price_won='17900',price_dollar='14.15',explanation='Deep fried shrimp',etc='null')
	new_menu=Menu(english_name='Modum twigim',korean_name='紐⑤몺��源�',price_won='18900',price_dollar='14.94',explanation='Assorted Deep-fried Dish',etc='null')
	new_menu=Menu(english_name='Chicken parmasan cream',korean_name='移섑궓�뚮쭏�고겕由�',price_won='18900',price_dollar='14.94',explanation='Chicken with parmasan cream',etc='null')
	new_menu=Menu(english_name='Gyuseujinikomi',korean_name='洹쒖뒪吏��덉퐫誘�',price_won='13000',price_dollar='10.28',explanation='Braised Beef Tendon',etc='null')
	new_menu=Menu(english_name='Butanokakeuni',korean_name='遺����몄뭅�щ땲',price_won='15000',price_dollar='11.86',explanation='Japanese Braised Pork in Soy Sauce',etc='null')
	new_menu=Menu(english_name='Torino garaage',korean_name='�좊━�멸��쇱븘寃�',price_won='15000',price_dollar='11.86',explanation='Deep fried chicken',etc='null')
	new_menu=Menu(english_name='Yennal yakisoba',korean_name='�쏅궇�쇳궎�뚮컮',price_won='13000',price_dollar='10.28',explanation='Oldstyle Stir-fried Soba Noodles',etc='null')
	new_menu=Menu(english_name='Tomato-kyuri-umesiso-dressing',korean_name='�좊쭏�좏걧由ъ슦硫붿떆�뚮뱶�덉떛',price_won='9500',price_dollar='7.51',explanation='Salad that made of tomato, cucumber, seaweed',etc='null')
	new_menu=Menu(english_name='Nato-Hiyaatko',korean_name='�ロ넗�고엳�쇱뼅肄�',price_won='9500',price_dollar='7.51',explanation='Soft tofu salad with nato',etc='null')
	new_menu=Menu(english_name='Age-dasinaseu',korean_name='�꾧쾶�ㅼ떆�섏뒪',price_won='9000',price_dollar='7.11',explanation='Deep fried egg plants that braised in soy sauce',etc='null')
	new_menu=Menu(english_name='Sisyamo gui',korean_name='�쒖깶紐④뎄��',price_won='8500',price_dollar='6.72',explanation='Grilled Capelin',etc='null')
	new_menu=Menu(english_name='Tejeu-keuri-gyoja',korean_name='�뚯쫰�щ━援먯옄',price_won='8500',price_dollar='6.72',explanation='Homemade grilled dumpling',etc='null')
	new_menu=Menu(english_name='Curry wa France bbang',korean_name='移대젅���꾨옉�ㅻ뭇',price_won='15000',price_dollar='11.86',explanation='French bread with curry sauce',etc='null')
	new_menu=Menu(english_name='Ninniku-oireuni',korean_name='�뚮땲�ъ삤�대Ⅴ��',price_won='15000',price_dollar='11.86',explanation='Similar with gambas al ajillo',etc='null')
	new_menu=Menu(english_name='Happy Ros챕 Tteokbokki',korean_name='�낆굪濡쒖젣�〓낭��(�낆텛泥�)',price_won='11500',price_dollar='9.09',explanation='Little spicy Ros챕 Tteokbokki topped with fried potato and bacon.',etc='null')
	new_menu=Menu(english_name='Don-gaseu plate',korean_name='�덇��� �뚮젅�댄듃(�낆텛泥�)',price_won='14000',price_dollar='11.07',explanation='Pork sirloin and tenderloin cutlet & fried mozzarella cheese & salad & steamed rice',etc='null')
	new_menu=Menu(english_name='Smile twibokk-i',korean_name='�ㅻ쭏�� ��蹂띠씠(�낆텛泥�)',price_won='9000',price_dollar='7.11',explanation='Tteokbokki with deep-fried rice cake',etc='null')
	new_menu=Menu(english_name='Happy Dangbokki',korean_name='�댄뵾 �밸낭��(�낆텛泥�)',price_won='9000',price_dollar='7.11',explanation='Tteokbokki with deep-fried glass noodles',etc='null')
	new_menu=Menu(english_name='Haechiseu myeonbokk-i',korean_name='�댁튂�� 硫대낭��',price_won='9000',price_dollar='7.11',explanation='Tteokbokki wth noodle(Signature basic Tteokbokki)',etc='null')
	new_menu=Menu(english_name='Twigim-udong',korean_name='��源��곕룞',price_won='8000',price_dollar='6.32',explanation='Tempura Udon',etc='null')
	new_menu=Menu(english_name='Mandu twigim',korean_name='留뚮몢��源�(1PL)',price_won='3500',price_dollar='2.77',explanation='Deep-fried Dumplings',etc='null')
	new_menu=Menu(english_name='Tong mozzarella twigim',korean_name='�듬え吏쒕젏�쇳�源�(3EA)',price_won='4000',price_dollar='3.16',explanation='Deep-fried Mozzarella cheese',etc='null')
	new_menu=Menu(english_name='Hashbrown',korean_name='�댁돩釉뚮씪��(4EA)',price_won='4000',price_dollar='3.16',explanation='Hash browns',etc='null')
	new_menu=Menu(english_name='Ya-chae twigim',korean_name='�쇱콈��源�(4EA)',price_won='4500',price_dollar='3.56',explanation='Deep-fried Vegetables',etc='null')
	new_menu=Menu(english_name='Cheese go-gu-ma croquette',korean_name='移섏쫰 怨좉뎄留� 怨좊줈耳�(4EA)',price_won='5000',price_dollar='3.95',explanation='Sweet potato cheese Croquette',etc='null')
	new_menu=Menu(english_name='Go-gu-ma twigim',korean_name='怨좉뎄留덊�源�(1PL)',price_won='5500',price_dollar='4.35',explanation='Deep-fried Sweet Potatoes',etc='null')
	new_menu=Menu(english_name='Gamja twigim',korean_name='媛먯옄��源�(1PL)',price_won='5000',price_dollar='3.95',explanation='Deep-fried potatoes',etc='null')
	new_menu=Menu(english_name='Sae-u twigim',korean_name='�덉슦��源�(4EA)',price_won='5500',price_dollar='4.35',explanation='Deep-fried shrimps',etc='null')
	new_menu=Menu(english_name='Haebppi poteto chip',korean_name='�낆굪�ы뀒�좎묩(移섏쫰�ㅻ끂��, 移좊━ ��1)',price_won='5000',price_dollar='3.95',explanation='Deep-fried potatoes with seasoning. you can choose cheese snowing or chili seasoning',etc='null')
	new_menu=Menu(english_name='Hanchi twigim',korean_name='�쒖튂��源�(1PA)',price_won='9000',price_dollar='7.11',explanation='Deep-fried Calamari',etc='null')
	new_menu=Menu(english_name='Tong ma-neul twigim',korean_name='�� 留덈뒛��源�',price_won='4500',price_dollar='3.56',explanation='Deep-fried whole garlic',etc='null')
	new_menu=Menu(english_name='Ma-neul tteokbokk-i',korean_name='留덈뒛�〓낭��',price_won='8000',price_dollar='6.32',explanation='Tteokbokki topped with sliced garlic',etc='null')
	new_menu=Menu(english_name='Tong sae-u gimbab',korean_name='�듭깉�곗궡源�諛�',price_won='4500',price_dollar='3.56',explanation='Shrimp Gimbap',etc='null')
	new_menu=Menu(english_name='Don-ga-seu gimbab',korean_name='�덇퉴�ㅺ�諛�',price_won='4800',price_dollar='3.79',explanation='Pork cutlet Gimbap',etc='null')
	new_menu=Menu(english_name='Ma-neul gimbab',korean_name='留덈뒛源�諛�',price_won='4800',price_dollar='3.79',explanation='Garlic Gimbap',etc='null')
	new_menu=Menu(english_name='Chamchi-mayo-gimbab',korean_name='李몄튂留덉슂源�諛�',price_won='4800',price_dollar='3.79',explanation='Tuna and Mayonnaise Gimbap',etc='null')
	new_menu=Menu(english_name='Teunsilgimbab',korean_name='�쇱떎源�諛�',price_won='4500',price_dollar='3.56',explanation='Gimbap',etc='null')
	new_menu=Menu(english_name='Ge-sal twigim (4EA)',korean_name='寃뚯궡��源� (4媛�)',price_won='4500',price_dollar='3.56',explanation='Deep-fried Crab',etc='null')
	new_menu=Menu(english_name='Gogi-twigimmandu (8EA)',korean_name='怨좉린��源�留뚮몢8媛�',price_won='4500',price_dollar='3.56',explanation='Deep-fried meat dumplings',etc='null')
	new_menu=Menu(english_name='Yangpa twigim',korean_name='�묓뙆��源�',price_won='4500',price_dollar='3.56',explanation='Deep-fried Onion',etc='null')
	new_menu=Menu(english_name='Chabssal sundae',korean_name='李뱀��쒕�',price_won='3500',price_dollar='2.77',explanation='Blood Sausage with Sweet Rice',etc='null')
	new_menu=Menu(english_name='Wang don-gaseu',korean_name='�뺣룉源뚯뒪',price_won='7000',price_dollar='5.53',explanation='Pork cutlet',etc='null')
	new_menu=Menu(english_name='Busanjinjja-eomuk (2EA)',korean_name='遺��곗쭊吏쒖뼱臾� 2媛�',price_won='2000',price_dollar='1.58',explanation='Fish cake',etc='null')
	new_menu=Menu(english_name='I-inbun jeukseok tteokbokk-i',korean_name='2�몃텇 利됱꽍�〓낭��',price_won='14000',price_dollar='11.07',explanation='Tabletop Tteokbokki for 2 people',etc='null')
	new_menu=Menu(english_name='Sam-inbun jeukseoktteokbokk-i',korean_name='3�몃텇 利됱꽍�〓낭��',price_won='19000',price_dollar='15.02',explanation='Tabletop Tteokbokki for 3 people',etc='null')
	new_menu=Menu(english_name='Sa-inbun jeukseoktteokbokk-i',korean_name='4�몃텇 利됱꽍�〓낭��',price_won='24000',price_dollar='18.97',explanation='Tabletop Tteokbokki for 4 people',etc='null')
	new_menu=Menu(english_name='Cheese tteok',korean_name='移섏쫰�� (8EA)',price_won='2000',price_dollar='1.58',explanation='Extra Rice Cake with Cheese Filling',etc='null')
	new_menu=Menu(english_name='Sausage',korean_name='�뚯꽭吏�',price_won='2500',price_dollar='1.98',explanation='Extra Sausage',etc='null')
	new_menu=Menu(english_name='Mozzarella cheese',korean_name='紐⑥쭨�먮씪移섏쫰',price_won='2500',price_dollar='1.98',explanation='Extra Mozzarella Cheese',etc='null')
	new_menu=Menu(english_name='Original spam',korean_name='�ㅻ━吏��� �ㅽ렓',price_won='3000',price_dollar='2.37',explanation='Extra Spam',etc='null')
	new_menu=Menu(english_name='Gye-ran',korean_name='怨꾨�',price_won='600',price_dollar='0.47',explanation='Extra steamed egg',etc='null')
	new_menu=Menu(english_name='Ra-myeon sari',korean_name='�쇰㈃�щ━',price_won='1000',price_dollar='0.79',explanation='Extra Ramyeon Noodles',etc='null')
	new_menu=Menu(english_name='Jjol-myeon sari',korean_name='已꾨㈃�щ━',price_won='1000',price_dollar='0.79',explanation='Extra Chewy Noodle',etc='null')
	new_menu=Menu(english_name='Tteok sari',korean_name='�≪궗由�(20EA)',price_won='2000',price_dollar='1.58',explanation='Extra Rice Cake',etc='null')
	new_menu=Menu(english_name='Gu-un odeng',korean_name='援ъ슫�ㅻ럢',price_won='2000',price_dollar='1.58',explanation='Extra Grilled Fish Cake',etc='null')
	new_menu=Menu(english_name='Jamja sujebi',korean_name='�좎옄�섏젣鍮�',price_won='2000',price_dollar='1.58',explanation='Extra Hand-pulled Potato Dough',etc='null')
	new_menu=Menu(english_name='Coca cola',korean_name='肄붿뭅肄쒕씪',price_won='2000',price_dollar='1.58',explanation='Coke',etc='null')
	new_menu=Menu(english_name='Cider',korean_name='�ъ씠��',price_won='2000',price_dollar='1.58',explanation='Cider',etc='null')
	new_menu=Menu(english_name='Milki-seu',korean_name='諛��ㅼ뒪',price_won='2000',price_dollar='1.58',explanation='Cider that mixed with milk',etc='null')
	new_menu=Menu(english_name='Welchs podo',korean_name='�곗튂�ㅽ룷��',price_won='2000',price_dollar='1.58',explanation='Welch's grape',etc='null')
	new_menu=Menu(english_name='Welchs cheongpodo',korean_name='�곗튂�ㅼ껌�щ룄',price_won='2000',price_dollar='1.58',explanation='Welch's muskat',etc='null')
	new_menu=Menu(english_name='Fanta pine',korean_name='�섑��뚯씤',price_won='2000',price_dollar='1.58',explanation='Fanta pineapple',etc='null')
	new_menu=Menu(english_name='Fanta podo',korean_name='�섑��щ룄',price_won='2000',price_dollar='1.58',explanation='Fanta grape',etc='null')
	new_menu=Menu(english_name='Fanta orange',korean_name='�섑��ㅻ젋吏�',price_won='2000',price_dollar='1.58',explanation='Fanta Orange',etc='null')
	new_menu=Menu(english_name='Trevi-lemon',korean_name='�몃젅鍮�-�덈が',price_won='2000',price_dollar='1.58',explanation='',etc='null')
	new_menu=Menu(english_name='Ripton',korean_name='由쏀넠',price_won='2000',price_dollar='1.58',explanation='',etc='null')
	new_menu=Menu(english_name='Mountain dew',korean_name='留덉슫�대�',price_won='2000',price_dollar='1.58',explanation='',etc='null')
	new_menu=Menu(english_name='Gal-a-mandeun-bae',korean_name='媛덉븘留뚮뱶諛�',price_won='2000',price_dollar='1.58',explanation='Pear beverage',etc='null')
	new_menu=Menu(english_name='Cass',korean_name='移댁뒪',price_won='4000',price_dollar='3.16',explanation='',etc='null')
	new_menu=Menu(english_name='Terra',korean_name='�뚮씪',price_won='4000',price_dollar='3.16',explanation='',etc='null')
	new_menu=Menu(english_name='Kloud',korean_name='�대씪�곕뱶',price_won='4000',price_dollar='3.16',explanation='',etc='null')
	new_menu=Menu(english_name='Somersby',korean_name='�쒕㉧�ㅻ퉬',price_won='6500',price_dollar='5.14',explanation='Apple flavor cider',etc='null')
	new_menu=Menu(english_name='Meat-bokki',korean_name='誘명듃蹂띠씠(2-3��)',price_won='16000',price_dollar='12.65',explanation='"Ingredient with rice cake, grilled meat, Cheddar cheese, fish cake, spring onion, steamed quaill egg, deep-fried yaki dumpling, deep-fried laver rolls and vegi(?)Tabletop Tteokbokki with deep broth and signature sauce & meat toping"',etc='null')
	new_menu=Menu(english_name='Sea-bokki',korean_name='�⑤낭��(2-3��)',price_won='23000',price_dollar='18.18',explanation='"Ingredient with rice cake, whole octopus, chewy noodle, mussel, pen shell, fish cake, spring onion, steamed quaill egg, deep-fried yaki dumpling, deep-fried laver rolls, fried crab stick and vegi(?)Tabletop Tteokbokki with seafood broth, octopus, scallop, mussel"',etc='null')
	new_menu=Menu(english_name='Mini crab garaage',korean_name='誘몃땲�щ옪 媛��쇱븘寃�',price_won='6000',price_dollar='4.74',explanation='Deep-fried mini crab',etc='null')
	new_menu=Menu(english_name='Chicken garaage',korean_name='移섑궓 媛��쇱븘寃�',price_won='9000',price_dollar='7.11',explanation='Deep-fried Chicken',etc='null')
	new_menu=Menu(english_name='Tongmaneul ttongjib garaage',korean_name='�듬쭏�섎삦吏� 媛��쇱븘寃�',price_won='9000',price_dollar='7.11',explanation='Deep-fried garlic and chicken gizzards with soy sauce',etc='null')
	new_menu=Menu(english_name='Gimchi bokk-eumbap',korean_name='源�移섎낭�뚮갈',price_won='3000',price_dollar='2.37',explanation='Kimchi Fried Rice',etc='null')
	new_menu=Menu(english_name='Bingsul',korean_name='鍮숈닠',price_won='9000',price_dollar='7.11',explanation='Low alcohol cocktail with cool and sweet-sour flavor',etc='null')
	new_menu=Menu(english_name='Ros챕 jeukseok tteokbokk-i',korean_name='濡쒖젣 利됱꽍�〓낭��',price_won='10000',price_dollar='7.91',explanation='Tabletop Ros챕 Tteokbokki',etc='null')
	new_menu=Menu(english_name='Modum mandu',korean_name='紐⑤몺留뚮몢',price_won='10000',price_dollar='7.91',explanation='Assorted dumplings',etc='null')
	new_menu=Menu(english_name='Tteokbokk-i',korean_name='�〓낭��',price_won='7000',price_dollar='5.53',explanation='Tteokbokki',etc='null')
	new_menu=Menu(english_name='Gogi jijimmandu',korean_name='怨좉린 吏�吏먮쭔��',price_won='6500',price_dollar='5.14',explanation='Fried Meat Dumplings',etc='null')
	new_menu=Menu(english_name='Gogi jjin mandu',korean_name='怨좉린 李먮쭔��',price_won='6500',price_dollar='5.14',explanation='Steamed Meat Dumplings',etc='null')
	new_menu=Menu(english_name='Gimchi jijimmandu',korean_name='源�移� 吏�吏먮쭔��',price_won='6500',price_dollar='5.14',explanation='Fried Kimchi Dumplings',etc='null')
	new_menu=Menu(english_name='Gimchi jjinmandu',korean_name='源�移� 李먮쭔��',price_won='6500',price_dollar='5.14',explanation='Steamed Kimchi Dumplings',etc='null')
	new_menu=Menu(english_name='Sutbul jijim mandu',korean_name='��텋 吏�吏� 留뚮몢',price_won='7500',price_dollar='5.93',explanation='Fried Rib Dumplings',etc='null')
	new_menu=Menu(english_name='Sae-u jijim mandu',korean_name='�덉슦 吏�吏� 留뚮몢',price_won='8000',price_dollar='6.32',explanation='Fried Shrimp Dumplings',etc='null')
	new_menu=Menu(english_name='Jjolmyeon',korean_name='已꾨㈃',price_won='7500',price_dollar='5.93',explanation='Spicy Chewy Noodles',etc='null')
	new_menu=Menu(english_name='Mae-kom je-yuk deopbap',korean_name='留ㅼ숴 �쒖쑁 ��갈',price_won='8000',price_dollar='6.32',explanation='Spicy Stir-fried Pork with Rice',etc='null')
	new_menu=Menu(english_name='Gimchi bokk-eumbap',korean_name='源�移� 蹂띠쓬諛�',price_won='8000',price_dollar='6.32',explanation='Kimchi Fried Rice',etc='null')
	new_menu=Menu(english_name='Mae-un jjajang tteokbokk-i',korean_name='留ㅼ슫 吏쒖옣 �〓낭��',price_won='7500',price_dollar='5.93',explanation='Spicy Tteokbokki cooked with Black Bean pesto',etc='null')
	new_menu=Menu(english_name='Truffle jijim mandu',korean_name='�몃윭�� 吏�吏� 留뚮몢',price_won='9000',price_dollar='7.11',explanation='Fried Truffle Dumpling with other mushrooms.',etc='null')
	new_menu=Menu(english_name='Gogi-gungjung mandu',korean_name='怨좉린沅곸쨷留뚮몢',price_won='6500',price_dollar='5.14',explanation='Steamed meat dumpling',etc='null')
	new_menu=Menu(english_name='Gimchi gungjungmandu',korean_name='源�移섍턿以묐쭔��',price_won='6500',price_dollar='5.14',explanation='Steamed kimchi meat dumpling',etc='null')
	new_menu=Menu(english_name='Ros챕 tteokbokk-i',korean_name='濡쒖젣 �〓낭��',price_won='8000',price_dollar='6.32',explanation='Ros챕 Tteokbokki',etc='null')
	new_menu=Menu(english_name='留덈�而ㅻ━�щ┝移섑궓',korean_name='Manyeo-curry cream chicken',price_won='20000',price_dollar='15.81',explanation='',etc='null')
	new_menu=Menu(english_name='�쒖궡移섑궓',korean_name='Sunsal chicken',price_won='11000',price_dollar='8.7',explanation='Fried Boneless Chicken',etc='null')
	new_menu=Menu(english_name='�꾨씪�대뱶移섑궓',korean_name='Fried chicken',price_won='10000',price_dollar='7.91',explanation='',etc='null')
	new_menu=Menu(english_name='�レ뒪�뚯씠�ㅼ튂��',korean_name='Hot spice chicken',price_won='10000',price_dollar='7.91',explanation='Hot Spicy Chicken',etc='null')
	new_menu=Menu(english_name='�ㅻ━',korean_name='Dari',price_won='11000',price_dollar='8.7',explanation='Deep-fried Chicken Drumsticks',etc='null')
	new_menu=Menu(english_name='�좉컻',korean_name='Nalgae',price_won='11000',price_dollar='8.7',explanation='Fried Chicken Wings',etc='null')
	new_menu=Menu(english_name='�쒕━�명듃',korean_name='Nanri set',price_won='19900',price_dollar='15.74',explanation='You can enjoy wiht one and half chicken, French fries and chicken salad(Actually the chicken is little small size). You can choose 3 meun among fried chicken, glazed fried chicken, glazed Mara sauce chicken, Soy Sauce Glazed Fried Chicken, spicy soy sauce glazed Fried Chicken',etc='null')
	new_menu=Menu(english_name='�쒖궡�명듃',korean_name='Sunsal set',price_won='19900',price_dollar='15.74',explanation='This is combo menu including French fries and chicken salad. You can choose 3 kinds of chicken menu(each half chicken).',etc='null')
	new_menu=Menu(english_name='留덈씪苑껋튂�⑥꽭��',korean_name='Marakkot-chicken-set',price_won='20900',price_dollar='16.53',explanation='This is combo menu including French fries and chicken salad. You can choose 3 kinds of chicken menu(each half chicken and this is boneless chicken).',etc='null')
	new_menu=Menu(english_name='1kg 泥좎씤3醫낆꽭��',korean_name='il-kg Cheol-in samjong set',price_won='19900',price_dollar='15.74',explanation='This menu includes a whole Mara chicken,and Chinese flower bun with condensed milk.',etc='null')
	new_menu=Menu(english_name='�꾨씪�대뱶移섑궓',korean_name='Fried chicken',price_won='17900',price_dollar='14.15',explanation='"Included fried chicken, glazed chicken and glazed soy sauce chicken.Can not change the menu."',etc='null')
	new_menu=Menu(english_name='�묐뀗移섑궓',korean_name='Yangnyeom chicken',price_won='18900',price_dollar='14.94',explanation='Glazed Fried Chicken',etc='null')
	new_menu=Menu(english_name='媛꾩옣移섑궓',korean_name='Ganjang chicken',price_won='18900',price_dollar='14.94',explanation='Soy Sauce Glazed Fried Chicken',etc='null')
	new_menu=Menu(english_name='�띻컝移섑궓',korean_name='Hong-gal chicken',price_won='18900',price_dollar='14.94',explanation='Glazed chicken with chilli sauce,garlic and chilli',etc='null')
	new_menu=Menu(english_name='留덈씪移섑궓',korean_name='Mara chicken',price_won='18900',price_dollar='14.94',explanation='Glazed Mara sauce chicken',etc='null')
	new_menu=Menu(english_name='��삦吏묓�源�',korean_name='Dak-ttongjib-twigim',price_won='9000',price_dollar='7.12',explanation='Deep fried chicken gizzard',etc='null')
	new_menu=Menu(english_name='怨좎텛��源�(4pc)',korean_name='Gochu-twigim',price_won='6000',price_dollar='4.74',explanation='Deep fried chili(4pc)',etc='null')
	new_menu=Menu(english_name='留뚮몢��源�(5pc)',korean_name='Mandu twigim',price_won='6000',price_dollar='4.74',explanation='Deep fried dumpling(5pc)',etc='null')
	new_menu=Menu(english_name='�곗쑀苑껊뭇��源�(7pc)',korean_name='Yeonyu kkotbbang twigim',price_won='6000',price_dollar='4.74',explanation='',etc='null')
	new_menu=Menu(english_name='怨좉뎄留덉뒪��(4pc)',korean_name='Goguma stick(4pc)',price_won='3000',price_dollar='2.37',explanation='Deep-fried Sweet Potato Sticks (4pc)',etc='null')
	new_menu=Menu(english_name='移섏쫰�ㅽ떛(4pc)',korean_name='cheese stick(4pc)',price_won='3000',price_dollar='2.37',explanation='Deep-fried Mozzarella Cheese Sticks(4pc)',etc='null')
	new_menu=Menu(english_name='�묐뀗媛먯옄 以�',korean_name='Yangnyeom gamja jung',price_won='3000',price_dollar='2.37',explanation='Seasoned deep fried potatoes - middle size',etc='null')
	new_menu=Menu(english_name='�묐뀗媛먯옄 ��',korean_name='Yangnyeom gamja dae',price_won='6000',price_dollar='4.74',explanation='Seasoned deep fried potatoes - largee size',etc='null')
	new_menu=Menu(english_name='諛섎쭏由� 移섑궓',korean_name='Ban-mari chicken',price_won='10000',price_dollar='7.91',explanation='Half Fried Chicken',etc='null')
	new_menu=Menu(english_name='�묐뀗諛섎쭏由� 移섑궓',korean_name='Yangnyeom ban-mari chicken',price_won='10000',price_dollar='7.91',explanation='Half Glazed Fried Chicken',etc='null')
	new_menu=Menu(english_name='怨듦린諛�',korean_name='Gonggi bap',price_won='1500',price_dollar='1.19',explanation='a bowl of steamed rice',etc='null')
	new_menu=Menu(english_name='�꾨＝吏��듬떗',korean_name='Nurungji tongdak',price_won='20000',price_dollar='15.81',explanation='This is a Korean-style barbecue that puts new glutinous rice in the stomach of a chicken and bakes it for 90 minutes with oak heat, then makes glutinous rice with nurungji on a hot stone plate.',etc='null')
	new_menu=Menu(english_name='移섏쫰 �꾨＝吏� �듬떗',korean_name='Cheese nurungji tongdak',price_won='23000',price_dollar='18.19',explanation='Rosted chicken with 99% of mozzarella cheese and scorched rice on stone plate.',etc='null')
	new_menu=Menu(english_name='�묐뀗 �꾨＝吏� �듬떗',korean_name='Yangnyeom nurungji tongdak',price_won='23000',price_dollar='18.19',explanation='Rosted chicken with deep sweet sauce and scorched rice on stone plate.',etc='null')
	new_menu=Menu(english_name='留덈뒛 �묐뀗 �꾨＝吏� �듬떗',korean_name='Maneul yangnyeom nurungji tongdak',price_won='24000',price_dollar='18.98',explanation='Rosted chicken with deep garlic sauce and scorched rice on stone plate.',etc='null')
	new_menu=Menu(english_name='留ㅼ슫 �묐뀗 �꾨＝吏� �듬떗',korean_name='Mae-un yangnyeom nurungji tongdak',price_won='23000',price_dollar='18.19',explanation='Rosted chicken with deep spicy sauce and scorched rice on stone plate. You can choose the spicy level.',etc='null')
	new_menu=Menu(english_name='�쇱�媛덈퉬',korean_name='Dwaeji galbi',price_won='24000',price_dollar='18.98',explanation='"Grilled Pork Ribs.If you want to order this marinated pork BBQ, you should reserve it. For more information, please contact the restaurant."',etc='null')
	new_menu=Menu(english_name='濡쒖젣�꾨＝吏� �듬떗',korean_name='Ros챕 nurungji tongdak',price_won='24000',price_dollar='18.98',explanation='Rosted chicken with rose sauce and scorched rice on stone plate.',etc='null')

		